import { supabase, supabaseConfigured } from './supabase';
export async function signInAdmin(email: string,password: string){if(!supabaseConfigured||!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;return data;}
export async function getAdminDashboard(){if(!supabase)throw new Error('Supabase no está configurado.');const [{data:profile},{data:bookings,error}]=await Promise.all([supabase.from('admin_profiles').select('display_name,active').single(),supabase.from('bookings').select('id,public_reference,preferred_date,participant_count,status,created_at,customers(full_name,email),routes(title)').order('created_at',{ascending:false}).limit(25)]);if(error)throw error;if(!profile?.active)throw new Error('La cuenta no tiene acceso administrativo activo.');return {profile,bookings:bookings??[]};}
export const bookingStatuses=['received','reviewing','confirmed','cancelled','completed'] as const; export type BookingStatus=typeof bookingStatuses[number]; export interface BookingFilters{page?:number;pageSize?:number;query?:string;routeId?:string;date?:string;status?:BookingStatus|'';}
export async function getBookingRoutes(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('routes').select('id,title').eq('status','published').in('status_label',['Ruta inicial','Disponible']).order('title');if(error)throw error;return data??[];}
export async function getBookings(f:BookingFilters={}){
  if(!supabase)throw new Error('Supabase no está configurado.');
  const page=Math.max(f.page??1,1),pageSize=f.pageSize??20;
  let q=supabase.from('bookings').select('id,public_reference,preferred_date,preferred_time,language,participant_count,modality,special_requests,internal_notes,status,created_at,updated_at,customers(full_name,email,phone),routes(id,title)',{count:'exact'}).order('created_at',{ascending:false});
  if(f.routeId)q=q.eq('route_id',f.routeId);if(f.date)q=q.eq('preferred_date',f.date);if(f.status)q=q.eq('status',f.status);
  if(f.query?.trim()){
    const term=f.query.trim().replace(/[%_,().]/g,' ').trim();
    const {data:customers,error:customerError}=await supabase.from('customers').select('id').or(`full_name.ilike.%${term}%,email.ilike.%${term}%`).limit(100);
    if(customerError)throw customerError;
    const ids=(customers??[]).map(item=>item.id);
    q=ids.length?q.or(`public_reference.ilike.%${term}%,customer_id.in.(${ids.join(',')})`):q.ilike('public_reference',`%${term}%`);
  }
  const {data,error,count}=await q.range((page-1)*pageSize,page*pageSize-1);if(error)throw error;return {bookings:data??[],total:count??0,page,pageSize};
}
export async function getBookingHistory(id:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('audit_log').select('id,action,details,created_at').eq('entity_type','booking').eq('entity_id',id).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function manageBooking(id:string,status:BookingStatus,notes:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('manage_booking',{p_booking_id:id,p_status:status,p_internal_notes:notes});if(error)throw error;return data;}
export async function getAdminRoutes(){if(!supabase)throw new Error('Supabase no está configurado.');const [{data:routes,error:routesError},{data:drafts,error:draftsError},{data:media,error:mediaError}]=await Promise.all([supabase.from('routes').select('id,slug,title,eyebrow,promise,full_description,status_label,display_duration,display_format,display_area,offered_languages,audience,display_starting_point,display_ending_point,includes,excludes,accessibility,display_price_individual,display_price_group,featured,status,sort_order,route_stops(title,sort_order),route_translations(*)').order('sort_order'),supabase.from('route_drafts').select('route_id,content,updated_at'),supabase.from('route_media').select('route_id,status').in('status',['draft','pending_removal'])]);if(routesError)throw routesError;if(draftsError)throw draftsError;if(mediaError)throw mediaError;const draftsByRoute=new Map((drafts??[]).map(d=>[d.route_id,d])),mediaRoutes=new Set((media??[]).map(item=>item.route_id));return (routes??[]).map(route=>({...route,draft:draftsByRoute.get(route.id)??null,hasMediaDraft:mediaRoutes.has(route.id)}));}
export async function saveRouteDraft(id:string,payload:Record<string,unknown>){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('save_route_draft',{p_route_id:id,p_payload:payload});if(error)throw error;return data;}
export async function publishRouteDraft(id:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('publish_route_draft',{p_route_id:id});if(error)throw error;const {error:deployError}=await supabase.functions.invoke('trigger-site-deploy');return data&&typeof data==='object'?{...data,deployStarted:!deployError}:data;}
export async function getRouteHistory(id:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('audit_log').select('id,action,details,created_at').eq('entity_type','route').eq('entity_id',id).eq('action','route_updated').order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function revertRouteRevision(auditId:number){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('revert_route_revision',{p_audit_id:auditId});if(error)throw error;const {error:deployError}=await supabase.functions.invoke('trigger-site-deploy');return data&&typeof data==='object'?{...data,deployStarted:!deployError}:data;}
export async function duplicateAdminRoute(id:string,title:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('duplicate_route',{p_route_id:id,p_new_title:title});if(error)throw error;return data;}
export async function getRouteMedia(routeId:string){if(!supabase)throw new Error('Supabase no está configurado.');const client=supabase;const {data,error}=await client.from('route_media').select('id,route_id,kind,role,storage_path,title,alt_text,mime_type,file_size_bytes,status,sort_order,created_at').eq('route_id',routeId).neq('status','archived').order('role').order('sort_order').order('created_at');if(error)throw error;return (data??[]).map(item=>({...item,publicUrl:client.storage.from('route-media').getPublicUrl(item.storage_path).data.publicUrl}));}
export async function uploadRouteMedia(routeId:string,file:File,role:'hero'|'gallery'|'attachment',title:string,altText:string){if(!supabase)throw new Error('Supabase no está configurado.');if(file.size<=0||file.size>26214400)throw new Error('El archivo debe pesar menos de 25 MB.');const image=file.type.startsWith('image/'),kind=image?'image':file.type.startsWith('audio/')?'audio':'document';if((role==='hero'||role==='gallery')&&!image)throw new Error('La imagen principal y la galería solo aceptan imágenes.');if(image&&!altText.trim())throw new Error('Escribe un texto alternativo para la imagen.');const extension=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,8)||'bin',storagePath=`${routeId}/${crypto.randomUUID()}.${extension}`;const {error:uploadError}=await supabase.storage.from('route-media').upload(storagePath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data,error}=await supabase.rpc('register_route_media',{p_route_id:routeId,p_kind:kind,p_role:role,p_storage_path:storagePath,p_title:title,p_alt_text:altText,p_mime_type:file.type,p_file_size_bytes:file.size});if(error){await supabase.storage.from('route-media').remove([storagePath]);throw error;}return data;}
export async function stageRouteMediaRemoval(mediaId:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('stage_route_media_removal',{p_media_id:mediaId});if(error)throw error;return data;}
export async function cancelRouteMediaRemoval(mediaId:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('cancel_route_media_removal',{p_media_id:mediaId});if(error)throw error;return data;}

export async function getAdminSiteDesign(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('get_admin_site_design');if(error)throw error;return data;}
export async function saveSiteDesignDraft(settings:unknown){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('save_site_design_draft',{p_settings:settings});if(error)throw error;return data;}
export async function publishSiteDesign(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('publish_site_design');if(error)throw error;const {error:deployError}=await supabase.functions.invoke('trigger-site-deploy');return {settings:data,deployStarted:!deployError};}
export async function discardSiteDesignDraft(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('discard_site_design_draft');if(error)throw error;return data;}
export async function getAdminMessages(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('messages').select('id,subject,body,inquiry_type,locale,read_at,created_at,customers(full_name,email,phone)').order('created_at',{ascending:false}).limit(200);if(error)throw error;return data??[];}
export async function markMessageRead(id:string,read=true){if(!supabase)throw new Error('Supabase no está configurado.');const {error}=await supabase.rpc('mark_message_read',{p_message_id:id,p_read:read});if(error)throw error;}
export async function getAdminReviews(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('reviews').select('id,display_name,rating,body,status,created_at,published_at,routes(title,slug),bookings(public_reference)').order('created_at',{ascending:false}).limit(200);if(error)throw error;return data??[];}
export async function setReviewStatus(id:string,status:'pending'|'published'|'rejected'){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('admin_set_review_status',{p_review_id:id,p_status:status});if(error)throw error;return data;}
export async function getAdminAvailability(routeId:string,from:string,to:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('get_admin_availability_overview',{p_route_id:routeId||null,p_from:from,p_to:to});if(error)throw error;return data??[];}
export async function getAdminAvailabilityStart(routeId:string){if(!supabase)throw new Error('Supabase no está configurado.');let query=supabase.from('bookings').select('preferred_date').order('preferred_date',{ascending:true}).limit(1);if(routeId)query=query.eq('route_id',routeId);const {data,error}=await query.maybeSingle();if(error)throw error;return data?.preferred_date??'';}
export async function setAvailability(routeId:string,date:string,time:string,capacity:number,open:boolean){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('admin_set_availability',{p_route_id:routeId,p_date:date,p_time:time,p_capacity:capacity,p_open:open});if(error)throw error;return data;}
export async function generateAvailabilityMonth(routeId:string,month:string,capacity:number){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('admin_generate_availability_month',{p_route_id:routeId,p_month:month,p_capacity:capacity});if(error)throw error;return data;}