export type FaqItem={question:string;answer:string};
export type EditorialLocaleCopy=Record<string,any>&{faqs:FaqItem[]};
export type EditorialCopy=Record<'es'|'en',EditorialLocaleCopy>;

export const defaultEditorialCopy:EditorialCopy={
  es:{
    brandName:'Rutas B',brandSubtitle:'de Barcelona',navRoutes:'Rutas',navCompare:'Comparar',navGuide:'Quién guía',navFaq:'Preguntas',navContact:'Contacto',navBook:'Reservar ruta',
    footerCopy:'Rutas culturales para entender Barcelona con contexto, cercanía y una mirada propia.',footerExplore:'Explorar',footerRoutes:'Todas las rutas',footerCompare:'Comparar rutas',footerBook:'Reservar una ruta',footerReviews:'Reseñas',footerInformation:'Información',footerContact:'Contacto',footerPrivacy:'Privacidad',footerTerms:'Condiciones',footerAdmin:'Acceso privado',footerPublications:'Publicaciones',
    routesKicker:'Catálogo inicial',routesTitle:'Encuentra tu ruta',routesIntro:'Tres formas distintas de leer Barcelona. Los datos pendientes están señalados con transparencia.',routesFilterAll:'Todas',routesFilterAvailable:'Disponibles',routesFilterPreparing:'En preparación',
    compareKicker:'Decide con claridad',compareTitle:'Compara las rutas',compareIntro:'La comparación muestra solo información confirmada. Lo que aún falta aparece como pendiente.',compareFeature:'Característica',compareArea:'Zona',compareDuration:'Duración',compareFormat:'Formato',compareLanguages:'Idiomas',compareIndividual:'Precio individual',compareGroup:'Grupo privado',compareAction:'Acción',compareView:'Ver ficha →',
    guideKicker:'Sobre Rutas B',guideTitle:'Una guía para mirar,\nno una lista para memorizar.',guideIntro:'Rutas B nace de una forma de entender la mediación cultural: claridad, contexto y conversación frente a la ciudad real.',guideSectionKicker:'Quién guía',guideName:'Daniel Pinto',guideBio:'Guía turístico en formación y sociólogo, con una mirada orientada a traducir fenómenos complejos en relatos claros, cercanos y útiles para quien visita Barcelona.',guideContactCopy:'Para consultas sobre las rutas, grupos privados o colaboraciones, puedes escribirnos mediante la página de contacto.',guideContactButton:'Contactar',guidePhotoUrl:'/images/guia/daniel-pinto.png',guidePhotoAlt:'Daniel Pinto, guía de Rutas B de Barcelona',guideProjectKicker:'El proyecto',guideProjectTitle:'Barcelona como experiencia que se puede aprender',guideProjectLead:'Cada ruta parte de una pregunta y organiza la mirada alrededor de ella. El objetivo no es acumular nombres y fechas, sino ayudar a reconocer relaciones: entre arquitectura y ciudad, patrimonio y vida cotidiana, historia y presente.',guideProjectBody:'Los recorridos se preparan mediante investigación, trabajo de terreno, pruebas de ejecución y adaptación al público. La información comercial que todavía no está cerrada se muestra como pendiente.',
    faqKicker:'Antes de reservar',faqTitle:'Preguntas frecuentes',faqIntro:'Respuestas claras sobre el funcionamiento inicial de Rutas B.',
    contactKicker:'Conversemos',contactPageTitle:'Contacto',contactPageIntro:'Para consultas generales, grupos, hoteles, agencias y colaboraciones.',contactDirectKicker:'Contacto directo',contactEmailLabel:'Correo electrónico',contactPhoneLabel:'Teléfono',contactNameLabel:'Nombre',contactEmailFieldLabel:'Correo electrónico',contactRequired:'obligatorio',contactTypeLabel:'Tipo de consulta',contactMessageLabel:'Mensaje',contactPrivacyLead:'He leído la',contactPrivacyLink:'política de privacidad',contactPrivacyTail:'y autorizo el uso de estos datos para responder mi consulta.',contactSummaryTitle:'Tu consulta',contactSummaryCopy:'El formulario enviará el mensaje directamente a Rutas B. No abrirá Outlook ni ninguna aplicación de correo.',contactSubmit:'Enviar consulta',
    bookingKicker:'Reserva sin pago en esta etapa',bookingTitle:'Reserva tu ruta',bookingIntro:'Elige la fecha y el horario. Las horas disponibles cambian automáticamente según el día del calendario.',bookingStep1:'1. Ruta',bookingStep2:'2. Contacto',bookingStep3:'3. Reserva',bookingExperienceLegend:'Elige la experiencia',bookingRouteLabel:'Ruta',bookingRoutePlaceholder:'Selecciona una ruta',bookingDateLabel:'Fecha',bookingTimeLabel:'Horario',bookingTimePlaceholder:'Selecciona primero una fecha',bookingTimeHelp:'Solo se muestran horarios disponibles.',bookingLanguageLabel:'Idioma de la ruta',bookingPeopleLabel:'Número de personas',bookingPartnerLabel:'Esta reserva también se realiza en nombre de un hotel, agencia o partner.',bookingContactLegend:'Datos de contacto',bookingNameLabel:'Nombre completo',bookingEmailLabel:'Correo electrónico',bookingPhoneLabel:'Teléfono',bookingOptional:'opcional',bookingNotesLabel:'Solicitud especial',bookingNotesPlaceholder:'Cuéntanos necesidades de movilidad, edades del grupo o cualquier contexto relevante.',bookingNotesLimit:'Máximo 1.000 caracteres',bookingPrivacyLead:'He leído la',bookingPrivacyLink:'política de privacidad',bookingPrivacyTail:'y autorizo el uso de estos datos para gestionar mi reserva.',bookingSummaryTitle:'Tu reserva',bookingSummaryCopy:'Al enviar este formulario, tu reserva quedará registrada. Recibirás por correo la referencia, el horario elegido y el punto de encuentro.',bookingSubmit:'Reservar ruta',
    privacyKicker:'Documento provisional',privacyTitle:'Política de privacidad',privacyWarning:'Este texto es una estructura pendiente de completar con la identidad legal, datos de contacto y revisión correspondiente antes de publicar formularios reales.',privacy1Title:'Datos que se solicitarán',privacy1Body:'Nombre, correo electrónico, teléfono opcional, ruta reservada, fecha, número de personas y cualquier información que decidas incluir en el campo de observaciones especiales.',privacy2Title:'Finalidad',privacy2Body:'Responder consultas y gestionar la reserva registrada.',privacy3Title:'Información sensible',privacy3Body:'No incluyas datos de salud ni otra información especialmente sensible salvo que sea imprescindible para adaptar la experiencia. En ese caso se definirá un tratamiento específico antes de activar el sistema.',privacy4Title:'Conservación y derechos',privacy4Body:'Los plazos, el responsable del tratamiento y el canal para ejercer derechos quedan pendientes de completar.',
    termsKicker:'Documento provisional',termsTitle:'Condiciones básicas',termsWarning:'Pendiente de completar antes del lanzamiento comercial. No constituye todavía una oferta contractual.',terms1Title:'Reservas',terms1Body:'El envío del formulario registra la reserva y genera una referencia. No se realiza ningún cobro en esta etapa.',terms2Title:'Precios',terms2Body:'Los precios que aparezcan como pendientes no deben interpretarse como gratuitos. La tarifa y lo que incluye se comunicarán antes de confirmar.',terms3Title:'Cambios y cancelaciones',terms3Body:'La política definitiva queda pendiente de decisión.',terms4Title:'Condiciones del recorrido',terms4Body:'Los puntos exactos y el orden pueden ajustarse por aforo, obras, eventos, condiciones meteorológicas o seguridad del grupo.',
    publicationsKicker:'Cuaderno de Rutas B',publicationsTitle:'Historias para seguir mirando',publicationsIntro:'Notas de campo, arquitectura, historia urbana y claves para recorrer Barcelona con contexto.',publicationsEmpty:'Aún no hay publicaciones visibles.',publicationsReadMore:'Leer publicación →',publicationsBack:'Volver a publicaciones',reviewsTrustTitle:'Opiniones con origen comprobable',reviewsTrust1:'Reserva comprobada',reviewsTrust2:'Correo y referencia privados',reviewsTrust3:'Sin testimonios inventados',reviewsReferenceLabel:'Referencia de reserva',reviewsEmailLabel:'Correo de la reserva',reviewsDisplayNameLabel:'Nombre que se mostrará',reviewsRatingLabel:'Valoración',reviewsRatingPlaceholder:'Selecciona',reviewsBodyLabel:'Reseña',reviewsPrivacy:'Autorizo la publicación del nombre indicado y del texto de la reseña. Mi correo y mi referencia no se publicarán.',reviewsSubmit:'Enviar reseña',confirmationMode:'Reserva completada',confirmationTitle:'Gracias por elegir Rutas B',confirmationCopy:'Tu reserva está registrada. Guarda estos datos; también los recibirás por correo electrónico.',confirmationReference:'Referencia',confirmationRoute:'Ruta',confirmationDate:'Fecha',confirmationTime:'Horario elegido',confirmationMeeting:'Punto de encuentro: frente al restaurante KFC — Gaudí',confirmationAddress:'Dirección: Avinguda de Gaudí, 2, 08025 Barcelona',confirmationTransport:'Transporte público: Metro Sagrada Família (L2 y L5)',confirmationReturn:'Volver a Rutas B',confirmationEmailWarning:'La reserva quedó registrada, pero el correo no pudo enviarse. Contáctanos indicando tu referencia.',
    faqs:[
      {question:'¿Al enviar el formulario queda hecha la reserva?',answer:'Sí. Solo puedes elegir fechas y horas disponibles. Al enviarlo, la reserva queda registrada y recibes por correo la referencia, el horario y el punto de encuentro.'},
      {question:'¿Debo pagar al enviar el formulario?',answer:'No. La primera versión no procesa pagos ni solicita datos bancarios.'},
      {question:'¿En qué idiomas se ofrecen las rutas?',answer:'Las rutas se ofrecen inicialmente en español e inglés. El guía comprende catalán y portugués, pero todavía no se anuncian como idiomas completos de guiado.'},
      {question:'¿Puedo reservar para un hotel, agencia o partner?',answer:'Sí. Marca la casilla correspondiente en el formulario. La reserva queda registrada con esa modalidad y la franja se bloquea automáticamente.'},
      {question:'¿La ruta de Sagrada Familia incluye entrada?',answer:'No. Es una ruta exterior alrededor de la basílica. Las entradas no están incluidas.'},
      {question:'¿Las rutas son accesibles?',answer:'Cada ficha indica el estado de la auditoría de accesibilidad. Antes de confirmar, revisaremos contigo cualquier necesidad concreta.'}
    ]
  },
  en:{
    brandName:'Rutas B',brandSubtitle:'de Barcelona',navRoutes:'Tours',navCompare:'Compare',navGuide:'Your guide',navFaq:'Questions',navContact:'Contact',navBook:'Book a tour',
    footerCopy:'Cultural tours to understand Barcelona through context, conversation and a distinctive point of view.',footerExplore:'Explore',footerRoutes:'All tours',footerCompare:'Compare tours',footerBook:'Book a tour',footerReviews:'Reviews',footerInformation:'Information',footerContact:'Contact',footerPrivacy:'Privacy',footerTerms:'Terms',footerAdmin:'Private access',footerPublications:'Journal',
    routesKicker:'Initial catalogue',routesTitle:'Find your tour',routesIntro:'Three different ways to read Barcelona. Information that is still pending is clearly marked.',routesFilterAll:'All',routesFilterAvailable:'Available',routesFilterPreparing:'In preparation',
    compareKicker:'Choose with clarity',compareTitle:'Compare the tours',compareIntro:'The comparison shows confirmed information. Details that remain open are marked as pending.',compareFeature:'Feature',compareArea:'Area',compareDuration:'Duration',compareFormat:'Format',compareLanguages:'Languages',compareIndividual:'Individual price',compareGroup:'Private group',compareAction:'Action',compareView:'View details →',
    guideKicker:'About Rutas B',guideTitle:'A guide to help you see,\nnot a list to memorise.',guideIntro:'Rutas B grows from a particular understanding of cultural mediation: clarity, context and conversation in front of the real city.',guideSectionKicker:'Your guide',guideName:'Daniel Pinto',guideBio:'Tour guide in training and sociologist, focused on turning complex phenomena into clear, approachable and useful stories for people visiting Barcelona.',guideContactCopy:'For questions about tours, private groups or collaborations, please use the contact page.',guideContactButton:'Contact',guidePhotoUrl:'/images/guia/daniel-pinto.png',guidePhotoAlt:'Daniel Pinto, guide at Rutas B de Barcelona',guideProjectKicker:'The project',guideProjectTitle:'Barcelona as an experience that can be learned',guideProjectLead:'Each tour begins with a question and organises the way we look around it. The aim is not to accumulate names and dates, but to recognise relationships between architecture and city, heritage and everyday life, history and the present.',guideProjectBody:'The tours are prepared through research, fieldwork, practical testing and adaptation to the audience. Commercial information that is not yet final is clearly marked as pending.',
    faqKicker:'Before booking',faqTitle:'Frequently asked questions',faqIntro:'Clear answers about how Rutas B currently works.',
    contactKicker:'Let us talk',contactPageTitle:'Contact',contactPageIntro:'For general enquiries, groups, hotels, agencies and collaborations.',contactDirectKicker:'Direct contact',contactEmailLabel:'Email',contactPhoneLabel:'Phone',contactNameLabel:'Name',contactEmailFieldLabel:'Email',contactRequired:'required',contactTypeLabel:'Type of enquiry',contactMessageLabel:'Message',contactPrivacyLead:'I have read the',contactPrivacyLink:'privacy policy',contactPrivacyTail:'and authorise the use of these details to answer my enquiry.',contactSummaryTitle:'Your enquiry',contactSummaryCopy:'The form sends your message directly to Rutas B. It will not open Outlook or any email application.',contactSubmit:'Send enquiry',
    bookingKicker:'No payment at this stage',bookingTitle:'Book your tour',bookingIntro:'Choose a date and time. Available time slots change automatically according to the selected day.',bookingStep1:'1. Tour',bookingStep2:'2. Contact',bookingStep3:'3. Booking',bookingExperienceLegend:'Choose the experience',bookingRouteLabel:'Tour',bookingRoutePlaceholder:'Select a tour',bookingDateLabel:'Date',bookingTimeLabel:'Time',bookingTimePlaceholder:'Select a date first',bookingTimeHelp:'Only currently available times are shown.',bookingLanguageLabel:'Tour language',bookingPeopleLabel:'Number of people',bookingPartnerLabel:'This booking is also being made on behalf of a hotel, agency or partner.',bookingContactLegend:'Contact details',bookingNameLabel:'Full name',bookingEmailLabel:'Email',bookingPhoneLabel:'Phone',bookingOptional:'optional',bookingNotesLabel:'Special request',bookingNotesPlaceholder:'Tell us about mobility needs, the ages in your group or any relevant context.',bookingNotesLimit:'Maximum 1,000 characters',bookingPrivacyLead:'I have read the',bookingPrivacyLink:'privacy policy',bookingPrivacyTail:'and authorise the use of these details to manage my booking.',bookingSummaryTitle:'Your booking',bookingSummaryCopy:'When you submit this form, your booking will be registered. You will receive the reference, selected time and meeting point by email.',bookingSubmit:'Book tour',
    privacyKicker:'Provisional document',privacyTitle:'Privacy policy',privacyWarning:'This is a provisional structure pending completion with the legal identity, contact details and appropriate review.',privacy1Title:'Data requested',privacy1Body:'Name, email address, optional phone number, selected tour, date, number of participants and any information you choose to include in the special requests field.',privacy2Title:'Purpose',privacy2Body:'To answer enquiries and manage the registered booking.',privacy3Title:'Sensitive information',privacy3Body:'Do not include health data or other particularly sensitive information unless it is essential to adapt the experience. A specific procedure will be defined before such processing is enabled.',privacy4Title:'Retention and rights',privacy4Body:'Retention periods, the data controller and the channel for exercising rights remain to be completed.',
    termsKicker:'Provisional document',termsTitle:'Basic terms',termsWarning:'To be completed before the commercial launch. This does not yet constitute a contractual offer.',terms1Title:'Bookings',terms1Body:'Submitting the form registers the booking and generates a reference. No payment is charged at this stage.',terms2Title:'Prices',terms2Body:'Prices marked as pending must not be interpreted as free. The price and included services will be communicated before any paid transaction.',terms3Title:'Changes and cancellations',terms3Body:'The final policy remains to be decided.',terms4Title:'Tour conditions',terms4Body:'Exact meeting points and the order of the route may be adjusted due to capacity, construction work, events, weather or group safety.',
    publicationsKicker:'Rutas B journal',publicationsTitle:'Stories for a closer look',publicationsIntro:'Field notes, architecture, urban history and ideas for exploring Barcelona with context.',publicationsEmpty:'There are no public posts yet.',publicationsReadMore:'Read article →',publicationsBack:'Back to journal',reviewsTrustTitle:'Reviews with a verifiable origin',reviewsTrust1:'Verified booking',reviewsTrust2:'Private email and reference',reviewsTrust3:'No invented testimonials',reviewsReferenceLabel:'Booking reference',reviewsEmailLabel:'Booking email',reviewsDisplayNameLabel:'Public display name',reviewsRatingLabel:'Rating',reviewsRatingPlaceholder:'Select',reviewsBodyLabel:'Review',reviewsPrivacy:'I authorise publication of the display name and review text. My email and booking reference will not be published.',reviewsSubmit:'Submit review',confirmationMode:'Booking completed',confirmationTitle:'Thank you for choosing Rutas B',confirmationCopy:'Your booking is registered. Keep these details; you will also receive them by email.',confirmationReference:'Reference',confirmationRoute:'Tour',confirmationDate:'Date',confirmationTime:'Selected time',confirmationMeeting:'Meeting point: in front of KFC — Gaudí',confirmationAddress:'Address: Avinguda de Gaudí, 2, 08025 Barcelona',confirmationTransport:'Public transport: Sagrada Família metro station (L2 and L5)',confirmationReturn:'Return to Rutas B',confirmationEmailWarning:'Your booking was registered, but the email could not be sent. Please contact us and include your reference.',
    faqs:[
      {question:'Does submitting the form register my booking?',answer:'Yes. The booking is registered and receives a unique reference. No payment is charged at this stage.'},
      {question:'Do I need to pay when submitting the form?',answer:'No. This version does not process payments or request bank details.'},
      {question:'Which languages are available?',answer:'Tours are initially offered in Spanish and English. The guide understands Catalan and Portuguese, but these are not yet advertised as full guiding languages.'},
      {question:'Can I book for a hotel, agency or partner?',answer:'Yes. Mark the corresponding box in the form. The booking is registered with that condition and the time slot is blocked automatically.'},
      {question:'Does the Sagrada Familia tour include admission?',answer:'No. It is an outdoor tour around the basilica. Admission tickets are not included.'},
      {question:'Are the tours accessible?',answer:'Each tour page describes the current accessibility information. Please contact us about any specific requirement.'}
    ]
  }
};

export function normalizeEditorialCopy(input:any):EditorialCopy{
  const result=structuredClone(defaultEditorialCopy);
  for(const locale of ['es','en'] as const){
    if(input?.[locale]&&typeof input[locale]==='object')Object.assign(result[locale],input[locale]);
    result[locale].faqs=Array.isArray(input?.[locale]?.faqs)?input[locale].faqs.filter((item:any)=>item&&typeof item.question==='string'&&typeof item.answer==='string').slice(0,30):result[locale].faqs;
  }
  return result;
}
