// @ts-nocheck
import { getAvailability, notifyBooking, submitBooking } from '../lib/booking';
const form=document.querySelector('[data-booking-form]');
if(form){
 const en=form.dataset.locale==='en',base=form.dataset.base||'/',root=en?base+'en/':base,text=(es,eng)=>en?eng:es,route=form.elements.route,dateInput=form.elements.date,timeSelect=form.elements.time,status=form.querySelector('[data-time-help]');
 const requested=new URLSearchParams(location.search).get('ruta');route.value=requested||'sagrada-familia';const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);dateInput.min=tomorrow.toISOString().slice(0,10);
 const loadTimes=async()=>{const day=dateInput.value;timeSelect.replaceChildren(new Option(day?text('Consultando horarios…','Loading times…'):text('Selecciona primero una fecha','Select a date first'),''));timeSelect.disabled=true;if(!day)return;status.textContent=text('Consultando disponibilidad…','Loading availability…');try{const slots=await getAvailability(route.value,day,day);timeSelect.replaceChildren(new Option(slots.length?text('Selecciona una hora','Select a time'):text('No hay horarios disponibles','No available times'),''));slots.forEach(slot=>{const remaining=Number(slot.capacity)-Number(slot.reserved_places),availability=remaining<3?text(`Quedan ${remaining} plazas`,`Only ${remaining} places left`):text('Disponible','Available');timeSelect.add(new Option(`${slot.slot_time} · ${availability}`,slot.slot_time))});timeSelect.disabled=!slots.length;status.textContent=slots.length?text('Solo se muestran las horas disponibles.','Only available times are shown.'):text('No hay disponibilidad para esta fecha. Prueba con otro día.','There is no availability on this date. Try another day.')}catch{status.textContent=text('No fue posible consultar la disponibilidad.','Availability could not be loaded.')}};
 dateInput.addEventListener('change',loadTimes);dateInput.addEventListener('click',()=>{try{dateInput.showPicker?.()}catch{}});route.addEventListener('change',()=>{dateInput.value='';loadTimes()});
 form.addEventListener('submit',async event=>{event.preventDefault();let valid=true;form.querySelectorAll('[data-error-for]').forEach(n=>n.textContent='');[...form.elements].forEach(field=>{if(field.willValidate&&!field.checkValidity()){valid=false;const out=form.querySelector(`[data-error-for="${field.name}"]`);if(out)out.textContent=field.validity.valueMissing?text('Completa este campo.','Complete this field.'):text('Revisa este dato.','Check this value.')}});if(!valid){form.querySelector(':invalid')?.focus();return}const button=form.querySelector('.submit-button'),message=form.querySelector('[data-form-message]');button.disabled=true;button.textContent=text('Reservando…','Booking…');message.hidden=true;try{const e=form.elements,result=await submitBooking({route:e.route.value,date:e.date.value,time:e.time.value,language:e.language.value,people:Number(e.people.value),modality:e.partnerBooking.checked?'partner':'shared',name:e.name.value.trim(),email:e.email.value.trim(),phone:e.phone.value.trim(),notes:e.notes.value.trim(),website:e.website.value});const emailSent=result.mode==='connected'?await notifyBooking(result.reference):false,routeTitle=e.route.options[e.route.selectedIndex]?.textContent||e.route.value,timeLabel=e.time.options[e.time.selectedIndex]?.textContent||e.time.value;sessionStorage.setItem('rutasb-last-request',JSON.stringify({route:e.route.value,routeTitle,name:e.name.value,date:e.date.value,time:e.time.value,timeLabel,reference:result.reference,mode:result.mode,duplicate:result.duplicate,emailSent,locale:en?'en':'es'}));location.href=root+'confirmacion/'}catch{message.textContent=text('Ese horario acaba de dejar de estar disponible o no pudimos registrar la reserva. Elige otra hora e inténtalo nuevamente.','That time has just become unavailable, or the booking could not be registered. Choose another time and try again.');message.hidden=false;button.disabled=false;button.textContent=text('Reservar ruta','Book tour');await loadTimes()}});
}