// @ts-nocheck
import { getAvailability, notifyBooking, submitBooking } from '../lib/booking';
const form=document.querySelector('[data-booking-form]');
if(form){
 const en=form.dataset.locale==='en',base=form.dataset.base||'/',root=en?base+'en/':base,text=(es,eng)=>en?eng:es;
 const route=form.elements.route,dateInput=form.elements.date,timeSelect=form.elements.time,calendar=form.querySelector('[data-public-calendar]'),grid=form.querySelector('[data-calendar-grid]'),title=form.querySelector('[data-calendar-title]'),status=form.querySelector('[data-calendar-status]');
 let month=new Date();month=new Date(month.getFullYear(),month.getMonth(),1);let slots=[];
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const range=()=>{const from=iso(month),to=iso(new Date(month.getFullYear(),month.getMonth()+1,0));return{from,to}};
 const setTimes=(day)=>{const previous=timeSelect.value;timeSelect.replaceChildren(new Option(text('Selecciona una hora','Select a time'),''));const available=slots.filter(x=>x.slot_date===day);available.forEach(x=>timeSelect.add(new Option(`${x.slot_time} · ${Number(x.capacity)-Number(x.reserved_places)} ${text('plazas','places')}`,x.slot_time)));timeSelect.disabled=!available.length;if(available.some(x=>x.slot_time===previous))timeSelect.value=previous;};
 const selectDay=day=>{dateInput.value=day;setTimes(day);grid.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.date===day));status.textContent=text(`Fecha elegida: ${new Intl.DateTimeFormat('es-ES',{dateStyle:'long'}).format(new Date(day+'T12:00:00'))}`,`Selected date: ${new Intl.DateTimeFormat('en-GB',{dateStyle:'long'}).format(new Date(day+'T12:00:00'))}`);};
 const render=()=>{grid.innerHTML='';title.textContent=new Intl.DateTimeFormat(en?'en-GB':'es-ES',{month:'long',year:'numeric'}).format(month);const first=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),availableDays=new Set(slots.map(x=>x.slot_date));for(let i=0;i<first;i++){const blank=document.createElement('span');blank.className='calendar-blank';grid.append(blank)}for(let d=1;d<=days;d++){const dt=new Date(month.getFullYear(),month.getMonth(),d),day=iso(dt),button=document.createElement('button');button.type='button';button.dataset.date=day;button.innerHTML=`<strong>${d}</strong><small>${slots.filter(x=>x.slot_date===day).map(x=>x.slot_time).join(' · ')}</small>`;button.disabled=!availableDays.has(day);button.className=availableDays.has(day)?'available':'unavailable';button.onclick=()=>selectDay(day);grid.append(button)}calendar.querySelector('[data-month-prev]').disabled=month<=new Date(new Date().getFullYear(),new Date().getMonth(),1);};
 const load=async()=>{dateInput.value='';setTimes('');if(!route.value){slots=[];render();status.textContent=text('Elige una ruta para consultar su calendario.','Choose a tour to see its calendar.');return}status.textContent=text('Consultando disponibilidad…','Loading availability…');const {from,to}=range();try{slots=await getAvailability(route.value,from,to);render();status.textContent=slots.length?text('Selecciona uno de los días marcados.','Choose one of the highlighted days.'):text('No hay horarios publicados en este mes.','No times are published for this month.')}catch{slots=[];render();status.textContent=text('No fue posible cargar la disponibilidad.','Availability could not be loaded.')}};
 calendar.querySelector('[data-month-prev]').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);load()};calendar.querySelector('[data-month-next]').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);load()};route.addEventListener('change',load);
 const selected=new URLSearchParams(location.search).get('ruta');if(selected)route.value=selected;load();
 form.addEventListener('submit',async event=>{event.preventDefault();let valid=true;form.querySelectorAll('[data-error-for]').forEach(n=>n.textContent='');if(!dateInput.value){valid=false;form.querySelector('[data-error-for="date"]').textContent=text('Selecciona una fecha disponible.','Choose an available date.')}[...form.elements].forEach(field=>{if(field.willValidate&&!field.checkValidity()){valid=false;const out=form.querySelector(`[data-error-for="${field.name}"]`);if(out)out.textContent=field.validity.valueMissing?text('Completa este campo.','Complete this field.'):text('Revisa este dato.','Check this value.')}});if(!valid){form.querySelector(':invalid')?.focus();return}const button=form.querySelector('.submit-button'),message=form.querySelector('[data-form-message]');button.disabled=true;button.textContent=text('Reservando…','Booking…');message.hidden=true;try{const e=form.elements,result=await submitBooking({route:e.route.value,date:e.date.value,time:e.time.value,language:e.language.value,people:Number(e.people.value),modality:e.partnerBooking.checked?'partner':'private',name:e.name.value.trim(),email:e.email.value.trim(),phone:e.phone.value.trim(),notes:e.notes.value.trim(),website:e.website.value});const emailSent=result.mode==='connected'?await notifyBooking(result.reference):false,routeTitle=e.route.options[e.route.selectedIndex]?.textContent||e.route.value,timeLabel=e.time.options[e.time.selectedIndex]?.textContent||e.time.value;sessionStorage.setItem('rutasb-last-request',JSON.stringify({route:e.route.value,routeTitle,name:e.name.value,date:e.date.value,time:e.time.value,timeLabel,reference:result.reference,mode:result.mode,duplicate:result.duplicate,emailSent,locale:en?'en':'es'}));location.href=root+'confirmacion/'}catch(err){message.textContent=text('Ese horario acaba de dejar de estar disponible o no pudimos registrar la reserva. Actualiza el calendario e inténtalo nuevamente.','That time has just become unavailable, or the booking could not be registered. Refresh the calendar and try again.');message.hidden=false;button.disabled=false;button.textContent=text('Reservar ruta','Book tour');await load()}});
}