// @ts-nocheck
import { getPublishedReviews,submitVerifiedReview } from '../lib/reviews';

const root=document.querySelector('[data-reviews-app]');
if(root){
  const en=root.dataset.locale==='en',text=(es,enText)=>en?enText:es,list=root.querySelector('[data-reviews-list]'),empty=root.querySelector('[data-reviews-empty]'),form=root.querySelector('[data-review-form]'),status=root.querySelector('[data-review-status]');
  const render=async()=>{try{const reviews=await getPublishedReviews();list.innerHTML='';empty.hidden=reviews.length>0;reviews.forEach(review=>{const route=Array.isArray(review.routes)?review.routes[0]:review.routes,card=document.createElement('article');card.className='review-card';card.innerHTML=`<div class="review-stars" aria-label="${review.rating} ${text('de 5 estrellas','out of 5 stars')}">${'★'.repeat(review.rating)}${'☆'.repeat(5-review.rating)}</div><blockquote></blockquote><strong></strong><span></span>`;card.querySelector('blockquote').textContent=review.body;card.querySelector('strong').textContent=review.display_name;card.querySelector('span').textContent=route?.title||text('Ruta de Barcelona','Barcelona tour');list.append(card)})}catch{empty.textContent=text('No fue posible cargar las reseñas.','Reviews could not be loaded.');empty.hidden=false;}};
  await render();
  form?.addEventListener('submit',async event=>{event.preventDefault();status.hidden=true;if(!form.checkValidity()){form.reportValidity();return}const button=form.querySelector('[type="submit"]'),e=form.elements;button.disabled=true;try{await submitVerifiedReview({reference:e.reference.value.trim(),email:e.email.value.trim(),displayName:e.displayName.value.trim(),rating:Number(e.rating.value),body:e.body.value.trim(),privacy:e.privacy.checked,website:e.website.value});form.reset();status.textContent=text('Gracias. Tu reseña quedó pendiente de moderación antes de publicarse.','Thank you. Your review has been received and will be published after the booking is verified.');status.className='form-message success';status.hidden=false;}catch(error){const duplicate=String(error?.message||'').includes('review_already_exists'),unverified=String(error?.message||'').includes('booking_not_verified');status.textContent=duplicate?text('Esta reserva ya tiene una reseña.','This booking already has a review.'):unverified?text('No pudimos verificar esa referencia con el correo indicado. La reserva debe estar confirmada o completada.','We could not verify that reference and email. The booking must be confirmed or completed.'):text('No fue posible enviar la reseña. Revisa los datos e inténtalo nuevamente.','The review could not be submitted. Check the details and try again.');status.className='form-message error';status.hidden=false;}finally{button.disabled=false;}});
}
