-- Barcino day/night editorial repair authorised on 2026-08-11.
-- Preserves bookings, availability, prices, schedules and media.
do $$
declare
  v_day uuid;
  v_night uuid;
  v record;
begin
  select id into v_day from public.routes where slug='barcino';
  select id into v_night from public.routes where slug='barcino-nocturna';
  if v_day is null or v_night is null then raise exception 'barcino_routes_required'; end if;

  update public.routes set
    title='Barcino medieval', eyebrow='Roma · ciudad medieval · capas habitables',
    promise='Descubre cómo Barcelona siguió habitando, transformando y contando la ciudad construida sobre Barcino.',
    short_description='Un recorrido por las capas romanas y medievales que todavía organizan el corazón de Barcelona.',
    full_description='Barcelona no sustituyó Barcino por una ciudad medieval: siguió construyendo sobre ella. Desde Plaça Nova, la ruta reconoce el antiguo límite romano, entra en los espacios de poder y representación de la catedral y Plaça del Rei, recupera la escala simbólica del Temple d’August y termina en Plaça Sant Jaume. Más que una sucesión de monumentos, propone leer cómo distintas épocas ocuparon, transformaron y volvieron a explicar un mismo centro urbano.',
    status='published',status_label='En preparación',display_duration='Duración por definir',display_format='Ruta exterior guiada',display_area='Barri Gòtic',
    display_starting_point='Plaça Nova',display_ending_point='Plaça Sant Jaume',offered_languages=array['Español','English'],updated_at=now()
  where id=v_day;

  update public.routes set
    title='Barcino medieval · Nocturna', eyebrow='Roma · noche · ciudad en escena',
    promise='Descubre cómo la oscuridad, la iluminación y el silencio cambian la lectura de la ciudad antigua.',
    short_description='Una lectura nocturna de las capas romanas y medievales del Gòtic, cuando la ciudad cambia de escala y de ritmo.',
    full_description='De noche, el centro histórico deja ver otras relaciones entre arquitectura, poder y memoria. Desde Jaume I, el recorrido reconoce las murallas y Tapineria, observa el frontis de la catedral como una escena urbana y atraviesa Plaça del Rei y Plaça Sant Jaume. El Pont del Bisbe permite discutir la construcción moderna de la imagen gótica y el cierre en Plaça Nova devuelve la mirada a las puertas de Barcino. Es una experiencia independiente de la versión diurna, concebida para leer la ciudad mediante luz, sombra y silencio.',
    status='published',status_label='En preparación',display_duration='Duración por definir',display_format='Ruta exterior guiada nocturna',display_area='Barri Gòtic',
    display_starting_point='Metro Jaume I',display_ending_point='Plaça Nova',offered_languages=array['Español','English'],updated_at=now()
  where id=v_night;

  insert into public.route_translations(route_id,locale,title,eyebrow,promise,full_description,status_label,display_duration,display_format,display_area,offered_languages,audience,display_starting_point,display_ending_point,stops,includes,excludes,accessibility,display_price_individual,display_price_group)
  values
  (v_day,'en','Medieval Barcino','Rome · medieval city · inhabited layers','Discover how Barcelona continued to inhabit, transform and narrate the city built over Barcino.','Barcelona did not replace Barcino with a medieval city: it continued to build upon it. Starting at Plaça Nova, this route identifies the Roman boundary, enters the spaces of power and representation around the cathedral and Plaça del Rei, recovers the symbolic scale of the Temple of Augustus and ends at Plaça Sant Jaume. Rather than presenting a sequence of monuments, it explores how different periods occupied, transformed and reinterpreted the same urban centre.','In preparation','Duration to be confirmed','Guided outdoor tour','Gothic Quarter',array['Spanish','English'],array['Cultural travellers','Small groups','Educational programmes'],'Plaça Nova','Plaça Sant Jaume',array['Entrance to Barcino','Casa de l’Ardiaca','Cathedral façade','Palau del Lloctinent and Plaça del Rei','Temple of Augustus','Plaça Sant Jaume'],array['Live guide','Urban and historical interpretation'],array['Admission tickets','Transport'],'Outdoor urban route.',null,null),
  (v_night,'en','Medieval Barcino · Night tour','Rome · night · the city as a stage','Discover how darkness, lighting and silence transform the way the ancient city is read.','At night, the historic centre reveals different relationships between architecture, power and memory. The route begins at Jaume I, follows the Roman walls and Tapineria, reads the cathedral façade as an urban stage and crosses Plaça del Rei and Plaça Sant Jaume. Pont del Bisbe opens a discussion about the modern construction of the Gothic image, while the final stop at Plaça Nova returns to the gates of Barcino. This is an independent counterpart to the daytime route, designed around light, shadow and silence.','In preparation','Duration to be confirmed','Guided outdoor night tour','Gothic Quarter',array['Spanish','English'],array['Cultural travellers','Small groups','Educational programmes'],'Jaume I metro station','Plaça Nova',array['Roman walls and Tapineria','Cathedral façade','Plaça del Rei','Plaça Sant Jaume','Pont del Bisbe','Gates of Barcino and Plaça Nova'],array['Live guide','Night-time urban interpretation'],array['Admission tickets','Transport'],'Outdoor urban night route.',null,null)
  on conflict(route_id,locale) do update set title=excluded.title,eyebrow=excluded.eyebrow,promise=excluded.promise,full_description=excluded.full_description,status_label=excluded.status_label,display_duration=excluded.display_duration,display_format=excluded.display_format,display_area=excluded.display_area,offered_languages=excluded.offered_languages,audience=excluded.audience,display_starting_point=excluded.display_starting_point,display_ending_point=excluded.display_ending_point,stops=excluded.stops,includes=excluded.includes,excludes=excluded.excludes,accessibility=excluded.accessibility,display_price_individual=excluded.display_price_individual,display_price_group=excluded.display_price_group,updated_at=now();

  insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,schedule_notes,translations)
  values
  (v_day,'Un recorrido por las capas romanas y medievales que todavía organizan el corazón de Barcelona.','Barcelona no sustituyó Barcino por una ciudad medieval: siguió construyendo sobre ella. La ruta reconoce el límite romano, los espacios de poder y representación y la continuidad del centro urbano.',array['Reconoce la huella romana dentro del Gòtic actual','Relaciona arquitectura, poder y memoria urbana','Lee distintas épocas en un mismo centro histórico'],array['Historia urbana','Roma','Barcelona medieval'],'Plaça Nova · Entrada a Barcino · Casa de l’Ardiaca · Frontis de la Catedral · Palau del Lloctinent y Plaça del Rei · Temple d’August · Plaça Sant Jaume','Programación pendiente.',jsonb_build_object('en',jsonb_build_object('short_description','A route through the Roman and medieval layers that still organise the heart of Barcelona.','long_description','Barcelona did not replace Barcino with a medieval city: it continued to build upon it. The route identifies the Roman boundary, the spaces of power and representation, and the continuity of the urban centre.','highlights',jsonb_build_array('Identify the Roman city within today’s Gothic Quarter','Connect architecture, power and urban memory','Read different periods within the same historic centre'),'categories',jsonb_build_array('Urban history','Rome','Medieval Barcelona'),'itinerary_summary','Plaça Nova · Entrance to Barcino · Casa de l’Ardiaca · Cathedral façade · Palau del Lloctinent and Plaça del Rei · Temple of Augustus · Plaça Sant Jaume','schedule_notes','Schedule pending.'))),
  (v_night,'Una lectura nocturna de las capas romanas y medievales del Gòtic, cuando la ciudad cambia de escala y de ritmo.','La noche transforma el centro histórico en una secuencia de escenas. Luz, sombra y silencio permiten observar de otra manera las murallas, la catedral, las plazas del poder y la imagen construida del Gòtic.',array['Observa cómo la noche transforma la escala de la arquitectura','Relaciona iluminación, poder y representación','Distingue patrimonio medieval e imagen gótica reconstruida'],array['Historia urbana','Noche','Barcelona medieval'],'Jaume I · Murallas romanas y Tapineria · Frontis de la Catedral · Plaça del Rei · Plaça Sant Jaume · Pont del Bisbe · Puertas de Barcino y Plaça Nova','Programación pendiente.',jsonb_build_object('en',jsonb_build_object('short_description','A night-time reading of the Gothic Quarter’s Roman and medieval layers, as the city changes scale and rhythm.','long_description','Night transforms the historic centre into a sequence of urban scenes. Light, shadow and silence offer a different way to observe the walls, the cathedral, the squares of power and the constructed image of the Gothic Quarter.','highlights',jsonb_build_array('Observe how night transforms architectural scale','Connect lighting, power and representation','Distinguish medieval heritage from the reconstructed Gothic image'),'categories',jsonb_build_array('Urban history','Night','Medieval Barcelona'),'itinerary_summary','Jaume I · Roman walls and Tapineria · Cathedral façade · Plaça del Rei · Plaça Sant Jaume · Pont del Bisbe · Gates of Barcino and Plaça Nova','schedule_notes','Schedule pending.')))
  on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,schedule_notes=excluded.schedule_notes,translations=excluded.translations,updated_at=now();

  for v in select * from (values
    (v_day,0,'Entrada a Barcino','La muralla hace visible el límite de la colonia romana dentro de la ciudad actual.','Plaça Nova permite reconocer las torres, la puerta y la lógica defensiva de Barcino antes de entrar en las capas posteriores del centro urbano.','Entrance to Barcino','The wall reveals the boundary of the Roman colony within the present city.','Plaça Nova reveals the towers, gate and defensive logic of Barcino before the route enters the later layers of the urban centre.'),
    (v_day,1,'Casa de l’Ardiaca','El edificio muestra cómo una estructura posterior se apoya literalmente sobre la muralla romana.','Patio, trazado y materiales muestran la reutilización de la ciudad antigua y la continuidad física entre Barcino y la Barcelona medieval.','Casa de l’Ardiaca','The building shows how a later structure rests directly upon the Roman wall.','Its courtyard, layout and materials reveal the reuse of the ancient city and the physical continuity between Barcino and medieval Barcelona.'),
    (v_day,2,'Frontis de la Catedral','La fachada abre una conversación sobre representación, memoria y construcción de la imagen gótica.','El frente permite distinguir el edificio medieval de su fachada neogótica y entender cómo Barcelona volvió a imaginar su propio pasado.','Cathedral façade','The façade opens a discussion about representation, memory and the making of the Gothic image.','The cathedral front distinguishes the medieval building from its Neo-Gothic façade and shows how Barcelona reimagined its own past.'),
    (v_day,3,'Palau del Lloctinent y Plaça del Rei','El conjunto concentra arquitectura, autoridad y ceremonial en el centro medieval.','La plaza y el palacio permiten leer cómo el poder ocupó y organizó el espacio sobre las capas heredadas de la ciudad romana.','Palau del Lloctinent and Plaça del Rei','The ensemble concentrates architecture, authority and ceremony in the medieval centre.','The square and palace reveal how power occupied and organised space over the inherited layers of the Roman city.'),
    (v_day,4,'Temple d’August','Las columnas conservadas devuelven la escala simbólica del foro de Barcino.','El templo relaciona religión, poder y representación en el corazón de la colonia, dentro de una arquitectura posterior que hoy contiene sus restos.','Temple of Augustus','The surviving columns restore the symbolic scale of Barcino’s forum.','The temple connects religion, power and representation at the heart of the colony, inside a later architecture that now contains its remains.'),
    (v_day,5,'Plaça Sant Jaume','El centro político actual mantiene una continuidad urbana que atraviesa siglos.','La plaza cierra la ruta conectando el foro romano con instituciones, ceremonias y disputas posteriores por el centro simbólico de Barcelona.','Plaça Sant Jaume','Today’s political centre preserves an urban continuity spanning centuries.','The square closes the route by connecting the Roman forum with later institutions, ceremonies and disputes over Barcelona’s symbolic centre.'),
    (v_night,0,'Murallas romanas y Tapineria','La iluminación recorta el antiguo límite urbano y transforma la percepción de su escala.','Desde Jaume I, la ruta reconoce la muralla y avanza por Tapineria para observar cómo la noche convierte el borde romano en una escena urbana.','Roman walls and Tapineria','Lighting outlines the former urban boundary and transforms its perceived scale.','From Jaume I, the route follows the wall and Tapineria, where night turns the Roman boundary into an urban scene.'),
    (v_night,1,'Frontis de la Catedral','La fachada y la plaza cambian cuando disminuyen el tránsito y el ruido cotidiano.','La luz nocturna separa volúmenes, vacíos y decisiones escenográficas, y permite preguntar qué parte de la imagen gótica es medieval y cuál es posterior.','Cathedral façade','The façade and square change as everyday traffic and noise recede.','Night lighting separates volumes, voids and scenic choices, reopening the question of which parts of the Gothic image are medieval and which are later.'),
    (v_night,2,'Plaça del Rei','La arquitectura nocturna concentra poder, escala y memoria en una sola escena.','El conjunto permite observar cómo los edificios construyen una imagen de autoridad y cómo la iluminación contemporánea reorganiza esa lectura.','Plaça del Rei','Night architecture concentrates power, scale and memory in a single scene.','The ensemble shows how buildings construct an image of authority and how contemporary lighting reorganises that reading.'),
    (v_night,3,'Plaça Sant Jaume','La plaza más despejada permite leer con mayor claridad el espacio del poder.','El centro político aparece como un escenario cívico donde la continuidad del lugar convive con instituciones y símbolos de épocas diferentes.','Plaça Sant Jaume','The quieter square makes the space of power easier to read.','The political centre becomes a civic stage where continuity of place coexists with institutions and symbols from different periods.'),
    (v_night,4,'Pont del Bisbe','Uno de los iconos del Gòtic revela la construcción moderna de una imagen medieval.','La parada diferencia patrimonio histórico, intervención del siglo XX y memoria turística para entender cómo Barcelona también fabrica sus escenarios.','Pont del Bisbe','One of the Gothic Quarter’s icons reveals the modern construction of a medieval image.','This stop separates historic heritage, twentieth-century intervention and tourist memory to show how Barcelona also manufactures its urban scenes.'),
    (v_night,5,'Puertas de Barcino y Plaça Nova','El cierre devuelve la mirada al límite romano desde una ciudad ya transformada.','Plaça Nova reúne la puerta de Barcino, la fachada catedralicia y las capas posteriores para cerrar la experiencia como una lectura completa del centro.','Gates of Barcino and Plaça Nova','The final stop returns to the Roman boundary from a city already transformed.','Plaça Nova brings together Barcino’s gate, the cathedral façade and later layers, closing the experience as a complete reading of the centre.')
  ) as x(route_id,position,title_es,short_es,long_es,title_en,short_en,long_en) loop
    update public.route_stops set title=v.title_es,short_description=v.short_es,full_description=v.long_es,translations=jsonb_build_object('en',jsonb_build_object('title',v.title_en,'short_description',v.short_en,'full_description',v.long_en)) where route_id=v.route_id and sort_order=v.position;
    if not found then insert into public.route_stops(route_id,title,sort_order,short_description,full_description,translations) values(v.route_id,v.title_es,v.position,v.short_es,v.long_es,jsonb_build_object('en',jsonb_build_object('title',v.title_en,'short_description',v.short_en,'full_description',v.long_en))); end if;
  end loop;
end $$;
