-- Independent commercial routes, detailed stops and mixed media.
-- Preserves bookings, customers, schedules and audit history.

alter table public.route_product_profiles
  add column if not exists schedule_notes text,
  add column if not exists page_settings jsonb not null default '{}'::jsonb;

alter table public.route_stops
  add column if not exists media_paths text[] not null default '{}';

alter table public.route_media drop constraint if exists route_media_kind_check;
alter table public.route_media add constraint route_media_kind_check check(kind in ('image','video','document','audio','map'));

update storage.buckets set allowed_mime_types=array[
 'image/jpeg','image/png','image/webp','image/avif','video/mp4','video/quicktime',
 'application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','audio/mpeg','audio/mp4'
] where id='route-media';

drop policy if exists public_route_product_profiles on public.route_product_profiles;
create policy public_route_product_profiles on public.route_product_profiles for select
using(exists(select 1 from public.routes r where r.id=route_id and r.status='published'));
grant select(route_id,short_description,long_description,highlights,categories,itinerary_summary,booking_cutoff_hours,closure_dates,max_group_size,meeting_address,meeting_reference,meeting_instructions,meeting_transport,what_to_bring,cancellation_policy,translations,schedule_notes,page_settings,updated_at) on public.route_product_profiles to anon;

create or replace function public.register_route_media(p_route_id uuid,p_kind text,p_role text,p_storage_path text,p_title text,p_alt_text text,p_mime_type text,p_file_size_bytes bigint)
returns public.route_media language plpgsql security definer set search_path=public as $$
declare v_media public.route_media;
begin
 if not public.is_active_admin() then raise exception 'admin_access_required' using errcode='42501';end if;
 if p_kind not in('image','video','document','audio','map') then raise exception 'invalid_media_kind' using errcode='22023';end if;
 if p_role not in('hero','gallery','attachment') then raise exception 'invalid_media_role' using errcode='22023';end if;
 if p_role='hero' and p_kind<>'image' then raise exception 'hero_image_required' using errcode='22023';end if;
 if p_role='gallery' and p_kind not in('image','video') then raise exception 'gallery_media_required' using errcode='22023';end if;
 if p_kind in('image','video') and coalesce(trim(p_alt_text),'')='' then raise exception 'media_alt_required' using errcode='22023';end if;
 if p_file_size_bytes<=0 or p_file_size_bytes>26214400 then raise exception 'invalid_media_size' using errcode='22023';end if;
 if not exists(select 1 from public.routes where id=p_route_id) then raise exception 'route_not_found' using errcode='P0002';end if;
 if p_role='hero' then update public.route_media set status='archived' where route_id=p_route_id and role='hero' and status='draft';end if;
 insert into public.route_media(route_id,kind,role,storage_path,title,alt_text,mime_type,file_size_bytes)
 values(p_route_id,p_kind,p_role,p_storage_path,nullif(trim(p_title),''),nullif(trim(p_alt_text),''),p_mime_type,p_file_size_bytes) returning * into v_media;
 insert into public.audit_log(admin_id,action,entity_type,entity_id,details) values(auth.uid(),'route_media_registered','route',p_route_id::text,jsonb_build_object('media_id',v_media.id,'kind',v_media.kind,'role',v_media.role));
 return v_media;
end $$;
revoke all on function public.register_route_media(uuid,text,text,text,text,text,text,bigint) from public,anon;
grant execute on function public.register_route_media(uuid,text,text,text,text,text,text,bigint) to authenticated;

create or replace function public.publish_route_product_draft(p_route_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare v_draft jsonb;v_product jsonb;v_stop jsonb;v_i integer:=0;
begin
 if not public.is_active_admin() then raise exception 'admin_access_required' using errcode='42501';end if;
 select content into v_draft from public.route_drafts where route_id=p_route_id for update;
 if v_draft is null then return;end if;
 v_product:=coalesce(v_draft->'product_profile','{}'::jsonb);
 if v_draft?'product_profile' then
  insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,booking_cutoff_hours,closure_dates,max_group_size,meeting_address,meeting_reference,meeting_instructions,meeting_transport,what_to_bring,cancellation_policy,private_notes,translations,schedule_notes,page_settings)
  values(p_route_id,nullif(trim(v_product->>'short_description'),''),nullif(trim(v_product->>'long_description'),''),array(select jsonb_array_elements_text(coalesce(v_product->'highlights','[]'))),array(select jsonb_array_elements_text(coalesce(v_product->'categories','[]'))),nullif(trim(v_product->>'itinerary_summary'),''),nullif(v_product->>'booking_cutoff_hours','')::integer,array(select value::date from jsonb_array_elements_text(coalesce(v_product->'closure_dates','[]'))),nullif(v_product->>'max_group_size','')::integer,nullif(trim(v_product->>'meeting_address'),''),nullif(trim(v_product->>'meeting_reference'),''),nullif(trim(v_product->>'meeting_instructions'),''),nullif(trim(v_product->>'meeting_transport'),''),array(select jsonb_array_elements_text(coalesce(v_product->'what_to_bring','[]'))),nullif(trim(v_product->>'cancellation_policy'),''),nullif(trim(v_product->>'private_notes'),''),coalesce(v_product->'translations','{}'),nullif(trim(v_product->>'schedule_notes'),''),coalesce(v_product->'page_settings','{}'))
  on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,booking_cutoff_hours=excluded.booking_cutoff_hours,closure_dates=excluded.closure_dates,max_group_size=excluded.max_group_size,meeting_address=excluded.meeting_address,meeting_reference=excluded.meeting_reference,meeting_instructions=excluded.meeting_instructions,meeting_transport=excluded.meeting_transport,what_to_bring=excluded.what_to_bring,cancellation_policy=excluded.cancellation_policy,private_notes=excluded.private_notes,translations=excluded.translations,schedule_notes=excluded.schedule_notes,page_settings=excluded.page_settings,updated_at=now();
 end if;
 if v_draft?'stop_details' then
  delete from public.route_stops where route_id=p_route_id;
  for v_stop in select value from jsonb_array_elements(coalesce(v_draft->'stop_details','[]')) loop
   if nullif(trim(v_stop->>'title'),'') is not null then
    insert into public.route_stops(route_id,title,sort_order,short_description,full_description,duration_minutes,practical_info,accessibility,latitude,longitude,image_path,image_alt,translations,media_paths)
    values(p_route_id,trim(v_stop->>'title'),v_i,nullif(trim(v_stop->>'short_description'),''),nullif(trim(v_stop->>'full_description'),''),nullif(v_stop->>'duration_minutes','')::integer,nullif(trim(v_stop->>'practical_info'),''),nullif(trim(v_stop->>'accessibility'),''),nullif(v_stop->>'latitude','')::numeric,nullif(v_stop->>'longitude','')::numeric,nullif(trim(v_stop->>'image_path'),''),nullif(trim(v_stop->>'image_alt'),''),coalesce(v_stop->'translations','{}'),array(select jsonb_array_elements_text(coalesce(v_stop->'media_paths','[]'))));v_i:=v_i+1;
   end if;
  end loop;
 end if;
 if v_draft?'commercial_variants' then delete from public.route_commercial_variants where route_id=p_route_id;end if;
end $$;

create or replace function public.duplicate_route(p_route_id uuid,p_new_title text)
returns public.routes language plpgsql security definer set search_path=public as $$
declare v_source public.routes;v_copy public.routes;v_slug text;
begin
 if not public.is_active_admin() then raise exception 'admin_access_required' using errcode='42501';end if;
 if char_length(trim(p_new_title)) not between 2 and 160 then raise exception 'invalid_route_title' using errcode='22023';end if;
 select * into v_source from public.routes where id=p_route_id;if not found then raise exception 'route_not_found' using errcode='P0002';end if;
 v_slug:=trim(both '-' from regexp_replace(lower(trim(p_new_title)),'[^a-z0-9]+','-','g'))||'-'||substr(encode(extensions.gen_random_bytes(3),'hex'),1,6);
 insert into public.routes(slug,title,short_description,full_description,duration_minutes_min,duration_minutes_max,offered_languages,meeting_point_public,meeting_point_private,accessibility,includes,excludes,min_participants,max_participants,status,featured,sort_order,eyebrow,promise,status_label,display_duration,display_format,display_area,display_starting_point,display_ending_point,audience,display_price_individual,display_price_group,primary_image_path,primary_image_alt)
 select v_slug,trim(p_new_title),short_description,full_description,duration_minutes_min,duration_minutes_max,offered_languages,meeting_point_public,meeting_point_private,accessibility,includes,excludes,min_participants,max_participants,'draft',false,sort_order+1,eyebrow,promise,'Borrador',display_duration,display_format,display_area,display_starting_point,display_ending_point,audience,display_price_individual,display_price_group,primary_image_path,primary_image_alt from public.routes where id=p_route_id returning * into v_copy;
 insert into public.route_translations(route_id,locale,title,eyebrow,promise,full_description,status_label,display_duration,display_format,display_area,offered_languages,audience,display_starting_point,display_ending_point,stops,includes,excludes,accessibility,display_price_individual,display_price_group)
 select v_copy.id,locale,title,eyebrow,promise,full_description,'Draft',display_duration,display_format,display_area,offered_languages,audience,display_starting_point,display_ending_point,stops,includes,excludes,accessibility,display_price_individual,display_price_group from public.route_translations where route_id=p_route_id;
 insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,booking_cutoff_hours,closure_dates,max_group_size,meeting_address,meeting_reference,meeting_instructions,meeting_transport,what_to_bring,cancellation_policy,private_notes,translations,schedule_notes,page_settings)
 select v_copy.id,short_description,long_description,highlights,categories,itinerary_summary,booking_cutoff_hours,closure_dates,max_group_size,meeting_address,meeting_reference,meeting_instructions,meeting_transport,what_to_bring,cancellation_policy,private_notes,translations,schedule_notes,page_settings from public.route_product_profiles where route_id=p_route_id;
 insert into public.route_stops(route_id,title,sort_order,short_description,full_description,duration_minutes,practical_info,accessibility,latitude,longitude,image_path,image_alt,translations,media_paths)
 select v_copy.id,title,sort_order,short_description,full_description,duration_minutes,practical_info,accessibility,latitude,longitude,image_path,image_alt,translations,media_paths from public.route_stops where route_id=p_route_id;
 insert into public.audit_log(admin_id,action,entity_type,entity_id,details) values(auth.uid(),'route_duplicated','route',v_copy.id::text,jsonb_build_object('source_route_id',p_route_id,'structured_content',true,'media_requires_review',true));return v_copy;
end $$;
revoke all on function public.duplicate_route(uuid,text) from public,anon;grant execute on function public.duplicate_route(uuid,text) to authenticated;

-- Seed the independent day/night products and keep CafèBorn editable but hidden.
do $$
declare v_day uuid;v_night uuid;
begin
 select id into v_day from public.routes where slug='sagrada-familia';
 if v_day is null then raise exception 'sagrada_route_required';end if;
 update public.routes set title='De Gaudí a la Sagrada Família · Diurna',short_description='Una lectura exterior de la Sagrada Família con luz de día.',full_description='Una ruta exterior para comprender el proyecto de Gaudí a través de sus fachadas, su relación con la ciudad y las decisiones que siguen transformando el templo.',duration_minutes_min=75,duration_minutes_max=75,offered_languages=array['es','en'],min_participants=2,max_participants=12,status='published',featured=true,sort_order=10,eyebrow='Arquitectura · ciudad · obra viva',promise='Comprende la Sagrada Família más allá de la postal.',status_label='Disponible',display_duration='75 minutos aprox.',display_format='Ruta exterior guiada',display_area='Sagrada Família',display_starting_point='Avinguda de Gaudí, 2',display_ending_point='Fachada de la Gloria',audience=array['Viajeros culturales','Primera visita','Público interesado en arquitectura'],display_price_individual='20 € por persona',display_price_group=null,primary_image_path='/images/routes/sagrada-familia-diurna/hero.webp',primary_image_alt='Sagrada Família vista desde la Plaça de Gaudí durante la ruta diurna',updated_at=now() where id=v_day;
 insert into public.routes(slug,title,short_description,full_description,duration_minutes_min,duration_minutes_max,offered_languages,meeting_point_public,accessibility,includes,excludes,min_participants,max_participants,status,featured,sort_order,eyebrow,promise,status_label,display_duration,display_format,display_area,display_starting_point,display_ending_point,audience,display_price_individual,primary_image_path,primary_image_alt)
 values('sagrada-familia-nocturna','De Gaudí a la Sagrada Família · Nocturna','La Sagrada Família cambia cuando cae la noche.','Una ruta exterior nocturna para leer iluminación, volumen, sombras y simbolismo cuando el templo y su entorno adquieren otra presencia.',75,75,array['es','en'],'Avinguda de Gaudí, 2','Recorrido exterior urbano.',array['Guía en vivo','Recorrido exterior de 75 minutos'],array['Entrada al templo','Transporte','Comida y bebida'],2,12,'published',true,20,'Arquitectura · noche · percepción','Descubre lo que la noche revela en la Sagrada Família.','Disponible','75 minutos aprox.','Ruta exterior nocturna','Sagrada Família','Avinguda de Gaudí, 2','Fachada de la Gloria',array['Viajeros culturales','Fotografía nocturna','Público interesado en arquitectura'],'20 € por persona','/images/routes/sagrada-familia-nocturna/hero.webp','Sagrada Família iluminada durante la ruta nocturna')
 on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,full_description=excluded.full_description,duration_minutes_min=excluded.duration_minutes_min,duration_minutes_max=excluded.duration_minutes_max,offered_languages=excluded.offered_languages,accessibility=excluded.accessibility,includes=excluded.includes,excludes=excluded.excludes,min_participants=excluded.min_participants,max_participants=excluded.max_participants,status=excluded.status,featured=excluded.featured,sort_order=excluded.sort_order,eyebrow=excluded.eyebrow,promise=excluded.promise,status_label=excluded.status_label,display_duration=excluded.display_duration,display_format=excluded.display_format,display_area=excluded.display_area,display_starting_point=excluded.display_starting_point,display_ending_point=excluded.display_ending_point,audience=excluded.audience,display_price_individual=excluded.display_price_individual,display_price_group=null,primary_image_path=excluded.primary_image_path,primary_image_alt=excluded.primary_image_alt,updated_at=now() returning id into v_night;
 if v_night is null then select id into v_night from public.routes where slug='sagrada-familia-nocturna';end if;
 update public.routes set sort_order=30,title='Barcino medieval',status='published' where slug='barcino';
 update public.routes set sort_order=90,status='draft',featured=false where slug='cafeborn';

 insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,booking_cutoff_hours,max_group_size,meeting_address,meeting_reference,meeting_instructions,meeting_transport,what_to_bring,cancellation_policy,translations,schedule_notes,page_settings)
 values
 (v_day,'Una lectura exterior de la Sagrada Família con luz de día.','Comprende cómo fachadas, plazas y ciudad forman una obra todavía viva.',array['Cinco paradas exteriores','Lectura comparada de las fachadas','Contexto urbano y arquitectónico'],array['Arquitectura','Gaudí','Barcelona'],'Plaça de Gaudí → Nacimiento → ábside → Pasión → Gloria',12,12,'Avinguda de Gaudí, 2, 08025 Barcelona','Frente al restaurante KFC – Gaudí','Llega 10 minutos antes y busca la identificación de Rutas B.','Metro Sagrada Família (L2 y L5)',array['Calzado cómodo','Agua','Protección solar en verano'],'Cancelación gratuita hasta 24 horas antes.',jsonb_build_object('en',jsonb_build_object('short_description','An outdoor reading of Sagrada Família in daylight.','long_description','Understand how façades, squares and the city form a living work.','highlights',array['Five outdoor stops','A comparative reading of the façades','Urban and architectural context'],'meeting_instructions','Arrive 10 minutes early and look for the Rutas B sign.','meeting_transport','Sagrada Família metro station (L2 and L5)','schedule_notes','Monday to Friday at 18:00. Saturday and Sunday at 10:00, 12:00 and 18:00.')),'Lunes a viernes a las 18:00. Sábados y domingos a las 10:00, 12:00 y 18:00.',jsonb_build_object('gallery_mode','carousel','stops_media_mode','carousel','stops_display_mode','cards','show_highlights',true,'show_meeting_point',true,'show_accessibility',true)),
 (v_night,'La Sagrada Família cambia cuando cae la noche.','Lee iluminación, sombras, volumen y simbolismo desde una experiencia exterior nocturna.',array['Arquitectura bajo iluminación nocturna','Cinco lecturas exteriores','Video de la Fachada de la Pasión'],array['Arquitectura','Gaudí','Noche'],'Plaça de Gaudí → Nacimiento → ábside → Pasión → Gloria',12,12,'Avinguda de Gaudí, 2, 08025 Barcelona','Frente al restaurante KFC – Gaudí','Llega 10 minutos antes y busca la identificación de Rutas B.','Metro Sagrada Família (L2 y L5)',array['Calzado cómodo','Ropa adecuada a la temperatura'],'Cancelación gratuita hasta 24 horas antes.',jsonb_build_object('en',jsonb_build_object('short_description','Sagrada Família changes after dark.','long_description','Read lighting, shadow, volume and symbolism through an outdoor night experience.','highlights',array['Architecture under night lighting','Five outdoor readings','Passion Façade video'],'meeting_instructions','Arrive 10 minutes early and look for the Rutas B sign.','meeting_transport','Sagrada Família metro station (L2 and L5)','schedule_notes','Every day at 22:00.')),'Todos los días a las 22:00.',jsonb_build_object('gallery_mode','carousel','stops_media_mode','carousel','stops_display_mode','cards','show_highlights',true,'show_meeting_point',true,'show_accessibility',true))
 on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,booking_cutoff_hours=excluded.booking_cutoff_hours,max_group_size=excluded.max_group_size,meeting_address=excluded.meeting_address,meeting_reference=excluded.meeting_reference,meeting_instructions=excluded.meeting_instructions,meeting_transport=excluded.meeting_transport,what_to_bring=excluded.what_to_bring,cancellation_policy=excluded.cancellation_policy,translations=excluded.translations,schedule_notes=excluded.schedule_notes,page_settings=excluded.page_settings,updated_at=now();

 delete from public.route_stops where route_id in(v_day,v_night);
 insert into public.route_stops(route_id,title,sort_order,short_description,full_description,duration_minutes,practical_info,accessibility,image_alt,media_paths,translations) values
 (v_day,'Plaça de Gaudí',0,'La obra dentro del paisaje urbano.','Primera lectura del conjunto: escala, encuadre, relación con la plaza y transformación continua.',12,'Parada exterior.','Espacio urbano accesible.','Sagrada Família enmarcada por los árboles de la Plaça de Gaudí',array['/images/routes/sagrada-familia-diurna/plaza-gaudi.webp'],jsonb_build_object('en',jsonb_build_object('title','Plaça de Gaudí','short_description','The building within the urban landscape.','full_description','First reading of scale, framing, the square and ongoing transformation.'))),
 (v_day,'Fachada del Nacimiento',1,'Materia, naturaleza y relato.','Observamos cómo Gaudí convierte piedra, luz y formas naturales en una narración arquitectónica.',16,'Parada exterior frente a la fachada.','Pavimento urbano accesible.','Detalle de la Fachada del Nacimiento',array['/images/routes/sagrada-familia-diurna/fachada-nacimiento.webp'],jsonb_build_object('en',jsonb_build_object('title','Nativity Façade','short_description','Matter, nature and narrative.','full_description','How Gaudí turns stone, light and natural forms into architectural narrative.'))),
 (v_day,'Zona del ábside',2,'La transición entre fachadas.','Leemos estructura, continuidad y la manera en que el edificio se inserta en la manzana.',12,'Desplazamiento por acera.','Recorrido exterior urbano.','Vista contrapicada de las torres de la Sagrada Família',array['/images/routes/sagrada-familia-diurna/contrapicado-marca.webp'],jsonb_build_object('en',jsonb_build_object('title','Apse area','short_description','The transition between façades.','full_description','Structure, continuity and the building within its urban block.'))),
 (v_day,'Fachada de la Pasión',3,'Contraste, tensión y geometría.','Comparamos lenguajes arquitectónicos y la experiencia espacial de una fachada radicalmente distinta.',18,'Parada exterior.','Espacio urbano accesible.','Identificación de Rutas B ante la Sagrada Família',array['/images/routes/sagrada-familia-diurna/primer-plano-marca.webp'],jsonb_build_object('en',jsonb_build_object('title','Passion Façade','short_description','Contrast, tension and geometry.','full_description','A comparison of architectural languages and a radically different spatial experience.'))),
 (v_day,'Fachada de la Gloria',4,'La obra abierta hacia el futuro.','Cerramos relacionando proyecto, ciudad, construcción y las preguntas que permanecen abiertas.',17,'Cierre del recorrido.','Recorrido exterior urbano.','Sagrada Família y material identificativo de Rutas B',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Glory Façade','short_description','A work open to the future.','full_description','Project, city, construction and the questions that remain open.'))),
 (v_night,'Plaça de Gaudí',0,'El conjunto emerge de la oscuridad.','La distancia permite reconocer silueta, iluminación y relación con el vacío nocturno.',12,'Parada exterior nocturna.','Espacio urbano accesible.','Sagrada Família iluminada desde la Plaça de Gaudí',array['/images/routes/sagrada-familia-nocturna/fachada-nacimiento.webp'],jsonb_build_object('en',jsonb_build_object('title','Plaça de Gaudí','short_description','The complex emerges from darkness.','full_description','Distance reveals silhouette, lighting and night-time space.'))),
 (v_night,'Fachada del Nacimiento',1,'La luz selecciona el relieve.','La iluminación nocturna modifica jerarquías, sombras y detalles de la fachada.',15,'Parada exterior.','Pavimento urbano accesible.','Fachada del Nacimiento iluminada de noche',array['/images/routes/sagrada-familia-nocturna/fachada-nacimiento.webp'],jsonb_build_object('en',jsonb_build_object('title','Nativity Façade','short_description','Light selects the relief.','full_description','Night lighting changes hierarchy, shadow and detail.'))),
 (v_night,'Zona del ábside',2,'Volumen, vitrales y obra viva.','Los vitrales y la iluminación interior permiten leer el edificio como cuerpo activo.',15,'Desplazamiento por acera.','Recorrido exterior urbano.','Zona del ábside y vitrales iluminados',array['/images/routes/sagrada-familia-nocturna/zona-abside.webp'],jsonb_build_object('en',jsonb_build_object('title','Apse area','short_description','Volume, stained glass and a living work.','full_description','Stained glass and interior light reveal the building as an active body.'))),
 (v_night,'Fachada de la Pasión',3,'Escena, sombra y tensión.','La fachada adquiere una dimensión escénica donde geometría y sombra intensifican el relato.',18,'Parada exterior con apoyo audiovisual.','Espacio urbano accesible.','Fachada de la Pasión durante la noche',array['/videos/routes/sagrada-familia-nocturna/fachada-pasion.mp4'],jsonb_build_object('en',jsonb_build_object('title','Passion Façade','short_description','Scene, shadow and tension.','full_description','Geometry and shadow intensify the narrative at night.'))),
 (v_night,'Fachada de la Gloria',4,'Barcelona y el templo después de oscurecer.','El cierre conecta la experiencia nocturna con el futuro del proyecto y su entorno cotidiano.',15,'Cierre del recorrido.','Recorrido exterior urbano.','Vista nocturna de la Sagrada Família',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Glory Façade','short_description','Barcelona and the temple after dark.','full_description','The night experience connects with the future of the project and its everyday setting.')));

 insert into public.route_media(route_id,kind,role,storage_path,title,alt_text,mime_type,file_size_bytes,status,sort_order) values
 (v_day,'image','gallery','/images/routes/sagrada-familia-diurna/contrapicado-marca.webp','Contrapicado con la marca','Sagrada Família en contrapicado con identificación de Rutas B','image/webp',1,'published',10),
 (v_day,'image','gallery','/images/routes/sagrada-familia-diurna/fachada-nacimiento.webp','Fachada del Nacimiento','Fachada del Nacimiento durante la ruta diurna','image/webp',1,'published',20),
 (v_day,'image','gallery','/images/routes/sagrada-familia-diurna/plaza-gaudi.webp','Plaça de Gaudí','Sagrada Família vista desde la Plaça de Gaudí','image/webp',1,'published',30),
 (v_day,'image','gallery','/images/routes/sagrada-familia-diurna/primer-plano-marca.webp','Rutas B ante la Sagrada Família','Identificación de Rutas B ante la Sagrada Família','image/webp',1,'published',40),
 (v_night,'image','gallery','/images/routes/sagrada-familia-nocturna/fachada-nacimiento.webp','Fachada del Nacimiento nocturna','Fachada del Nacimiento iluminada de noche','image/webp',1,'published',10),
 (v_night,'image','gallery','/images/routes/sagrada-familia-nocturna/zona-abside.webp','Zona del ábside nocturna','Ábside, vitrales y torres iluminados de noche','image/webp',1,'published',20),
 (v_night,'video','gallery','/videos/routes/sagrada-familia-nocturna/fachada-pasion.mp4','Fachada de la Pasión en movimiento','Video vertical de la Fachada de la Pasión durante la noche','video/mp4',5731978,'published',30)
 on conflict(storage_path) do update set route_id=excluded.route_id,kind=excluded.kind,role=excluded.role,title=excluded.title,alt_text=excluded.alt_text,mime_type=excluded.mime_type,file_size_bytes=excluded.file_size_bytes,status='published',sort_order=excluded.sort_order,updated_at=now();
end $$;