-- P0: rutas editables coherentes, productos en preparaci?n y regla completa de paradas.
-- No modifica reservas, disponibilidad, usuarios ni pol?ticas existentes.

do $$
declare
  v_barcino uuid;
  v_barcino_night uuid;
  v_cerda uuid;
  v_born uuid;
begin
  select id into v_barcino from public.routes where slug='barcino';
  if v_barcino is null then raise exception 'barcino_route_required'; end if;

  update public.routes set
    title='Barcino medieval', short_description='Barcelona antes de Barcelona: murallas, poder y memoria urbana.',
    full_description='Un recorrido exterior por las capas romanas y medievales del G?tic para comprender c?mo la ciudad conserva, transforma y vuelve a narrar su pasado.',
    eyebrow='Roma ? ciudad medieval ? memoria urbana', promise='Entra en Barcelona por sus capas.',
    status='published', status_label='En preparaci?n', display_duration='75 minutos aprox.',
    display_format='Ruta exterior guiada', display_area='Barri G?tic',
    display_starting_point='Pla?a Nova', display_ending_point='Pla?a del Rei',
    offered_languages=array['es','en'], max_participants=12, featured=false, sort_order=30,
    primary_image_path='/images/barcino.jpg', primary_image_alt='Restos de la muralla romana de Barcelona'
  where id=v_barcino;

  insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,booking_cutoff_hours,max_group_size,meeting_address,meeting_reference,meeting_instructions,meeting_transport,what_to_bring,cancellation_policy,translations,schedule_notes,page_settings)
  values(v_barcino,
    'Barcelona antes de Barcelona: murallas, poder y memoria urbana.',
    'Una lectura guiada de las capas que conectan Barcino con la ciudad medieval. Las paradas permiten reconocer c?mo el poder, la defensa, la religi?n y la vida cotidiana fueron dando forma al centro hist?rico.',
    array['Muralla y puertas de Barcino','Transformaci?n de la ciudad medieval','Lectura urbana de plazas y edificios'],
    array['Historia','Roma','Edad Media','Barri G?tic'],
    'Pla?a Nova ? Portal del Bisbe ? Pla?a Sant Jaume ? Call ? Temple d?August ? Pla?a del Rei',
    12,12,'Pla?a Nova, Barcelona','Junto a las letras Barcino','Busca la identificaci?n de Rutas B.','Metro Jaume I (L4)',array['Calzado c?modo'],'Por definir antes de publicar reservas.',
    jsonb_build_object('en',jsonb_build_object(
      'short_description','Barcelona before Barcelona: walls, power and urban memory.',
      'long_description','A guided reading of the layers connecting Roman Barcino with the medieval city.',
      'highlights',array['Walls and gates of Barcino','The medieval transformation of the city','An urban reading of squares and buildings'],
      'itinerary_summary','Pla?a Nova ? Bishop?s Gate ? Pla?a Sant Jaume ? Jewish Quarter ? Temple of Augustus ? Pla?a del Rei',
      'meeting_instructions','Look for the Rutas B sign.','meeting_transport','Jaume I metro station (L4)')),
    'Programaci?n pendiente.',jsonb_build_object('gallery_mode','carousel','stops_media_mode','carousel','stops_display_mode','cards','show_highlights',true,'show_meeting_point',true,'show_accessibility',true))
  on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,max_group_size=excluded.max_group_size,meeting_address=excluded.meeting_address,meeting_reference=excluded.meeting_reference,meeting_instructions=excluded.meeting_instructions,meeting_transport=excluded.meeting_transport,translations=excluded.translations,schedule_notes=excluded.schedule_notes,page_settings=excluded.page_settings,updated_at=now();

  delete from public.route_stops where route_id=v_barcino;
  insert into public.route_stops(route_id,title,sort_order,short_description,full_description,practical_info,accessibility,image_alt,media_paths,translations) values
  (v_barcino,'Pla?a Nova y la puerta de Barcino',0,'El acceso monumental permite leer el l?mite entre la ciudad romana y sus expansiones posteriores.','La muralla, las torres y el trazado de la entrada introducen la escala y la l?gica defensiva de Barcino.','Parada exterior.','Espacio urbano accesible.','Muralla romana en Pla?a Nova',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Pla?a Nova and the gate of Barcino','short_description','The monumental entrance reveals the boundary between the Roman city and its later expansions.'))),
  (v_barcino,'Portal del Bisbe',1,'La imagen medieval del G?tic convive aqu? con estructuras y relatos de ?pocas distintas.','La parada permite distinguir patrimonio antiguo, recreaci?n hist?rica e identidad urbana construida.','Parada exterior.','Espacio urbano accesible.','Portal del Bisbe',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Bishop?s Gate','short_description','The medieval image of the Gothic Quarter coexists here with structures and stories from different periods.'))),
  (v_barcino,'Pla?a Sant Jaume',2,'El centro pol?tico actual mantiene una continuidad urbana que atraviesa siglos.','La plaza conecta el foro romano con las instituciones y ceremonias de la Barcelona posterior.','Parada exterior.','Espacio urbano accesible.','Pla?a Sant Jaume',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Pla?a Sant Jaume','short_description','Today?s political centre preserves an urban continuity spanning centuries.'))),
  (v_barcino,'El Call',3,'La trama estrecha conserva huellas de convivencia, segregaci?n y transformaci?n social.','Calles, nombres y vac?os ayudan a reconstruir la experiencia de la comunidad jud?a medieval sin convertirla en decorado.','Desplazamiento por calles estrechas.','Algunos tramos tienen pavimento irregular.','Calle del Call',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','The Jewish Quarter','short_description','The narrow urban fabric preserves traces of coexistence, segregation and social change.'))),
  (v_barcino,'Temple d?August',4,'Las columnas conservadas hacen visible la escala simb?lica del foro de Barcino.','El templo permite relacionar religi?n, poder y representaci?n en el coraz?n de la ciudad romana.','Acceso sujeto al horario del espacio.','Acceso interior con condiciones propias.','Columnas del Temple d?August',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Temple of Augustus','short_description','The surviving columns reveal the symbolic scale of Barcino?s forum.'))),
  (v_barcino,'Pla?a del Rei',5,'El cierre re?ne poder, arquitectura y memoria en uno de los conjuntos m?s densos del G?tic.','La plaza permite observar c?mo cada ?poca se apoya en la anterior y reorganiza su significado.','Parada exterior final.','Pavimento hist?rico irregular.','Pla?a del Rei',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Pla?a del Rei','short_description','The final stop brings together power, architecture and memory in one of the Gothic Quarter?s densest ensembles.')));

  insert into public.routes(slug,title,short_description,full_description,duration_minutes_min,duration_minutes_max,offered_languages,meeting_point_public,meeting_point_private,accessibility,includes,excludes,min_participants,max_participants,status,featured,sort_order,eyebrow,promise,status_label,display_duration,display_format,display_area,display_starting_point,display_ending_point,audience,display_price_individual,display_price_group,primary_image_path,primary_image_alt)
  values('barcino-nocturna','Barcino medieval ? Nocturna','Las capas antiguas del G?tic bajo otra luz.','Una ruta exterior nocturna que utiliza sombra, silencio y perspectiva para leer las huellas romanas y medievales del centro hist?rico.',75,75,array['es','en'],'Pla?a Nova',null,'Recorrido exterior urbano.',array['Gu?a en vivo'],array['Entradas','Transporte'],2,12,'published',false,40,'Roma ? noche ? memoria urbana','Descubre c?mo cambia la ciudad antigua despu?s de oscurecer.','En preparaci?n','75 minutos aprox.','Ruta exterior nocturna','Barri G?tic','Pla?a Nova','Pla?a del Rei',array['Viajeros culturales'],null,null,'/images/barcino.jpg','Muralla romana de Barcelona al comienzo de la ruta nocturna')
  on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,full_description=excluded.full_description,status='published',status_label='En preparaci?n',featured=false,sort_order=40,updated_at=now()
  returning id into v_barcino_night;

  insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,max_group_size,translations,schedule_notes,page_settings)
  values(v_barcino_night,'Las capas antiguas del G?tic bajo otra luz.','Una lectura nocturna independiente de Barcino y la ciudad medieval, preparada para convertirse en producto comercial cuando est?n cerrados horario, precio y operaci?n.',array['Muralla nocturna','Call y plazas despu?s de oscurecer','Arquitectura y memoria'],array['Historia','Noche','Barri G?tic'],'Pla?a Nova ? Portal del Bisbe ? Sant Jaume ? Call ? Temple d?August ? Pla?a del Rei',12,jsonb_build_object('en',jsonb_build_object('short_description','The ancient layers of the Gothic Quarter under a different light.','long_description','An independent night reading of Barcino and the medieval city.')),'Programaci?n pendiente.',jsonb_build_object('gallery_mode','carousel','stops_media_mode','carousel','stops_display_mode','cards','show_highlights',true,'show_meeting_point',false,'show_accessibility',true))
  on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,max_group_size=excluded.max_group_size,translations=excluded.translations,schedule_notes=excluded.schedule_notes,page_settings=excluded.page_settings,updated_at=now();

  delete from public.route_stops where route_id=v_barcino_night;
  insert into public.route_stops(route_id,title,sort_order,short_description,full_description,media_paths,translations) values
  (v_barcino_night,'Pla?a Nova y la muralla',0,'La iluminaci?n recorta la frontera de la antigua ciudad y cambia la percepci?n de su escala.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Pla?a Nova and the Roman wall','short_description','Lighting outlines the boundary of the ancient city and changes its perceived scale.'))),
  (v_barcino_night,'Portal del Bisbe',1,'El portal funciona como una escena donde se cruzan historia, imagen y construcci?n del G?tic.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Bishop?s Gate','short_description','The gate becomes a scene where history, image and the making of the Gothic Quarter intersect.'))),
  (v_barcino_night,'Pla?a Sant Jaume',2,'La plaza vac?a permite leer con mayor claridad el espacio del poder.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Pla?a Sant Jaume','short_description','The quieter square makes the space of power easier to read.'))),
  (v_barcino_night,'El Call',3,'La noche devuelve escala y silencio a una trama urbana marcada por presencias y ausencias.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','The Jewish Quarter','short_description','Night restores scale and silence to an urban fabric marked by presence and absence.'))),
  (v_barcino_night,'Temple d?August',4,'El entorno cerrado concentra la lectura del templo y su dimensi?n simb?lica.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Temple of Augustus','short_description','The enclosed setting focuses attention on the temple and its symbolic dimension.'))),
  (v_barcino_night,'Pla?a del Rei',5,'La arquitectura nocturna cierra la ruta como una superposici?n visible de poderes y tiempos.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Pla?a del Rei','short_description','Night architecture closes the tour as a visible layering of powers and periods.')));

  insert into public.routes(slug,title,short_description,full_description,duration_minutes_min,duration_minutes_max,offered_languages,meeting_point_public,meeting_point_private,accessibility,includes,excludes,min_participants,max_participants,status,featured,sort_order,eyebrow,promise,status_label,display_duration,display_format,display_area,display_starting_point,display_ending_point,audience,display_price_individual,display_price_group,primary_image_path,primary_image_alt)
  values('cerda','Cerd?: la ciudad de 113 metros','Tres paradas para aprender a leer el Eixample.','Una versi?n compacta de la ruta Cerd? que convierte la cuadr?cula, la manzana y el interior urbano en herramientas para comprender el proyecto moderno de Barcelona.',75,75,array['es','en'],'Passeig de Gr?cia con Consell de Cent',null,'Recorrido exterior urbano.',array['Gu?a en vivo'],array['Entradas','Transporte'],2,12,'published',false,50,'Urbanismo ? Eixample ? ciudad moderna','La cuadr?cula deja de ser fondo y se convierte en una forma de mirar.','En preparaci?n','60?75 minutos aprox.','Ruta exterior guiada','Eixample','Passeig de Gr?cia / Consell de Cent','Jardins de la Torre de les Aig?es',array['Viajeros culturales','Estudiantes','P?blico interesado en urbanismo'],null,null,'/images/editorial/metodo-propio-eixample-horizontal-v2.webp','Vista a?rea de la trama del Eixample de Barcelona')
  on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,full_description=excluded.full_description,status='published',status_label='En preparaci?n',featured=false,sort_order=50,updated_at=now()
  returning id into v_cerda;

  insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,max_group_size,translations,schedule_notes,page_settings)
  values(v_cerda,'Tres paradas para aprender a leer el Eixample.','Producto compacto basado en la investigaci?n de la Ruta Cerd?. Presenta la l?gica de la cuadr?cula, la manzana y los interiores como una masterclass urbana caminable.',array['La manzana de 113 metros','Chaflanes y continuidad','El interior de manzana'],array['Urbanismo','Eixample','Cerd?'],'Passeig de Gr?cia / Consell de Cent ? Bruc 49 ? Jardins de la Torre de les Aig?es',12,jsonb_build_object('en',jsonb_build_object('short_description','Three stops to learn how to read the Eixample.','long_description','A compact urban masterclass on the grid, the block and its interiors.','highlights',array['The 113-metre block','Chamfers and continuity','The interior of the block'])),'Programaci?n pendiente.',jsonb_build_object('gallery_mode','carousel','stops_media_mode','carousel','stops_display_mode','cards','show_highlights',true,'show_meeting_point',false,'show_accessibility',true))
  on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,max_group_size=excluded.max_group_size,translations=excluded.translations,schedule_notes=excluded.schedule_notes,page_settings=excluded.page_settings,updated_at=now();

  delete from public.route_stops where route_id=v_cerda;
  insert into public.route_stops(route_id,title,sort_order,short_description,full_description,media_paths,translations) values
  (v_cerda,'Passeig de Gr?cia / Consell de Cent',0,'La primera parada convierte la cuadr?cula en una decisi?n pol?tica, t?cnica y cotidiana.','',array['/images/editorial/metodo-propio-eixample-horizontal-v2.webp'],jsonb_build_object('en',jsonb_build_object('title','Passeig de Gr?cia / Consell de Cent','short_description','The first stop turns the grid into a political, technical and everyday decision.'))),
  (v_cerda,'Carrer del Bruc, 49',1,'La fachada y el chafl?n permiten medir c?mo la unidad del plan admite diferencias.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','49 Carrer del Bruc','short_description','The fa?ade and chamfer show how a unified plan can still contain difference.'))),
  (v_cerda,'Jardins de la Torre de les Aig?es',2,'El interior de manzana revela la distancia entre el proyecto higienista y la ciudad construida.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Torre de les Aig?es Gardens','short_description','The block interior reveals the distance between the hygienist project and the city that was built.')));

  insert into public.routes(slug,title,short_description,full_description,duration_minutes_min,duration_minutes_max,offered_languages,meeting_point_public,meeting_point_private,accessibility,includes,excludes,min_participants,max_participants,status,featured,sort_order,eyebrow,promise,status_label,display_duration,display_format,display_area,display_starting_point,display_ending_point,audience,display_price_individual,display_price_group,primary_image_path,primary_image_alt)
  values('vista-previa-born','Vista Previa Born: Palau y Sant Pere','M?sica, comercio y vida urbana entre Santa Caterina y el Palau.','Un producto en desarrollo nacido de la investigaci?n propia de Caf?Born. Recorre el entorno de Santa Caterina y Sant Pere para llegar al Palau de la M?sica como cierre de una lectura cultural del barrio.',75,75,array['es','en'],'Mercat de Santa Caterina',null,'Recorrido exterior urbano.',array['Gu?a en vivo'],array['Entrada al Palau','Consumiciones','Transporte'],2,12,'published',false,60,'Cultura ? arquitectura ? vida urbana','Antes de entrar al Palau, aprende a leer el barrio que lo hizo posible.','En preparaci?n','75 minutos aprox.','Ruta exterior guiada','Sant Pere, Santa Caterina i la Ribera','Mercat de Santa Caterina','Caf? Palau',array['Viajeros culturales','M?sica y arquitectura','P?blico interesado en la vida urbana'],null,null,'/images/cafeborn.jpg','Entorno del Born y Sant Pere en Barcelona')
  on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,full_description=excluded.full_description,status='published',status_label='En preparaci?n',featured=false,sort_order=60,updated_at=now()
  returning id into v_born;

  insert into public.route_product_profiles(route_id,short_description,long_description,highlights,categories,itinerary_summary,max_group_size,translations,schedule_notes,page_settings)
  values(v_born,'M?sica, comercio y vida urbana entre Santa Caterina y el Palau.','Producto de vista previa basado en la investigaci?n propia de Caf?Born y Palau de la M?sica. Queda listo para depurar textos, operaci?n e im?genes antes de abrir reservas.',array['Mercado y transformaci?n urbana','Pasajes y vida cultural','Palau de la M?sica y Caf? Palau'],array['Cultura','Arquitectura','Born','Sant Pere'],'Mercat de Santa Caterina ? Sant Pere ? Antic Teatre ? Palau de la M?sica ? Caf? Palau',12,jsonb_build_object('en',jsonb_build_object('short_description','Music, commerce and urban life between Santa Caterina and the Palau.','long_description','A preview product built from original research on Caf?Born and the Palau de la M?sica.')),'Programaci?n pendiente.',jsonb_build_object('gallery_mode','carousel','stops_media_mode','carousel','stops_display_mode','cards','show_highlights',true,'show_meeting_point',false,'show_accessibility',true))
  on conflict(route_id) do update set short_description=excluded.short_description,long_description=excluded.long_description,highlights=excluded.highlights,categories=excluded.categories,itinerary_summary=excluded.itinerary_summary,max_group_size=excluded.max_group_size,translations=excluded.translations,schedule_notes=excluded.schedule_notes,page_settings=excluded.page_settings,updated_at=now();

  delete from public.route_stops where route_id=v_born;
  insert into public.route_stops(route_id,title,sort_order,short_description,full_description,media_paths,translations) values
  (v_born,'Mercat de Santa Caterina',0,'El mercado abre la conversaci?n sobre renovaci?n, comercio y continuidad barrial.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Santa Caterina Market','short_description','The market opens a conversation about renewal, commerce and neighbourhood continuity.'))),
  (v_born,'Sant Pere y sus pasajes',1,'La trama de calles y pasajes permite reconocer una ciudad cultural fuera de los grandes ejes.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Sant Pere and its passages','short_description','Streets and passages reveal a cultural city beyond the major avenues.'))),
  (v_born,'Antic Teatre',2,'Un espacio vivo conecta patrimonio construido, cultura independiente y usos actuales.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Antic Teatre','short_description','A living space connects built heritage, independent culture and present-day uses.'))),
  (v_born,'Palau de la M?sica',3,'La fachada convierte artes aplicadas, m?sica e identidad urbana en una escena p?blica.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Palau de la M?sica','short_description','The fa?ade turns applied arts, music and urban identity into a public scene.'))),
  (v_born,'Caf? Palau',4,'El cierre devuelve el monumento a la experiencia cotidiana del barrio.','',array[]::text[],jsonb_build_object('en',jsonb_build_object('title','Caf? Palau','short_description','The final stop returns the monument to the neighbourhood?s everyday experience.')));

insert into public.route_translations(route_id,locale,title,eyebrow,promise,full_description,status_label,display_duration,display_format,display_area,offered_languages,audience,display_starting_point,display_ending_point,stops,includes,excludes,accessibility,display_price_individual,display_price_group)
  values
  (v_barcino,'en','Medieval Barcino','Rome · medieval city · urban memory','Enter Barcelona through its layers.','An outdoor tour through the Roman and medieval layers of the Gothic Quarter.','In preparation','Approx. 75 minutes','Guided outdoor tour','Gothic Quarter',array['Spanish','English'],array['Cultural travellers'],'Plaça Nova','Plaça del Rei',array['Plaça Nova and the gate of Barcino','Bishop’s Gate','Plaça Sant Jaume','The Jewish Quarter','Temple of Augustus','Plaça del Rei'],array['Live guide'],array['Tickets','Transport'],'Urban outdoor route.',null,null),
  (v_barcino_night,'en','Medieval Barcino · Night','Rome · night · urban memory','Discover how the ancient city changes after dark.','An outdoor night tour through the Roman and medieval layers of the Gothic Quarter.','In preparation','Approx. 75 minutes','Guided outdoor night tour','Gothic Quarter',array['Spanish','English'],array['Cultural travellers'],'Plaça Nova','Plaça del Rei',array['Plaça Nova and the Roman wall','Bishop’s Gate','Plaça Sant Jaume','The Jewish Quarter','Temple of Augustus','Plaça del Rei'],array['Live guide'],array['Tickets','Transport'],'Urban outdoor route.',null,null),
  (v_cerda,'en','Cerdà: the 113-metre city','Urban planning · Eixample · modern city','The grid stops being a background and becomes a way of seeing.','A compact urban masterclass on the grid, the block and its interiors.','In preparation','Approx. 60–75 minutes','Guided outdoor tour','Eixample',array['Spanish','English'],array['Cultural travellers','Students'],'Passeig de Gràcia / Consell de Cent','Torre de les Aigües Gardens',array['Passeig de Gràcia / Consell de Cent','49 Carrer del Bruc','Torre de les Aigües Gardens'],array['Live guide'],array['Tickets','Transport'],'Urban outdoor route.',null,null),
  (v_born,'en','Born Preview: Palau and Sant Pere','Culture · architecture · urban life','Before entering the Palau, learn to read the neighbourhood that made it possible.','A preview product connecting Santa Caterina, Sant Pere and the Palau de la Música.','In preparation','Approx. 75 minutes','Guided outdoor tour','Sant Pere, Santa Caterina and La Ribera',array['Spanish','English'],array['Cultural travellers'],'Santa Caterina Market','Cafè Palau',array['Santa Caterina Market','Sant Pere and its passages','Antic Teatre','Palau de la Música','Cafè Palau'],array['Live guide'],array['Palau admission','Drinks','Transport'],'Urban outdoor route.',null,null)
  on conflict(route_id,locale) do update set title=excluded.title,eyebrow=excluded.eyebrow,promise=excluded.promise,full_description=excluded.full_description,status_label=excluded.status_label,display_duration=excluded.display_duration,display_format=excluded.display_format,display_area=excluded.display_area,offered_languages=excluded.offered_languages,audience=excluded.audience,display_starting_point=excluded.display_starting_point,display_ending_point=excluded.display_ending_point,stops=excluded.stops,includes=excluded.includes,excludes=excluded.excludes,accessibility=excluded.accessibility,display_price_individual=excluded.display_price_individual,display_price_group=excluded.display_price_group,updated_at=now();

  update public.routes set status='draft',featured=false,sort_order=90 where slug='cafeborn';
end $$;

